### ISSUE TITLE
调整一下bib等文件的存储位置

### ISSUE THREAD

**Issue by frostime** [WingDr/siyuan-plugin-citation#1]
README 里的文件说的很奇怪，`[工作空间]/data/siyuan-plugin-citation/data/`

> 在 [工作空间]/data/siyuan-plugin-citation/data/文件夹下，

我不知道你指的是不是 `[工作空间]/data/plugins/siyuan-plugin-citation` 。如果是的话，我需要提醒一下：plugin 目录下并不适合存储信息文件，用户只要卸载掉插件原先存储的文件就都没有了。

建议存在：

1. data/storage/petal/<pluginname> 目录下，这是插件的私有文件空间
2. data/public 下，这个同样可以作为资源目录来使用 [#8593](https://github.com/siyuan-note/siyuan/issues/8593)

**Comment by WingDr** [comment]
ok，感谢提醒，其实主要看哪里都没写不知道放在哪xs，马上这个版本就改了

**Comment by WingDr** [comment]
已经更新，新的路径请参考README，因为之后可能会有其它存储数据所以需要新建一个references文件夹
