### ISSUE TITLE
文献笔记的自动覆盖问题

### ISSUE THREAD

**Issue by wangfh5** [WingDr/siyuan-plugin-citation#14]
每当我`/add`插入文献引用, 选中之后, 它就会自动重建我相关文献笔记的内容. 这是一个非常危险的动作, 会丢失原有的编辑痕迹.

**Comment by WingDr** [comment]
> 每当我`/add`插入文献引用, 选中之后, 它就会自动重建我相关文献笔记的内容. 这是一个非常危险的动作, 会丢失原有的编辑痕迹.

是的，这个东西要跟你的数据来源进行同步，如果数据来源改变了，你重新插入时文献笔记也会重新刷新

你的问题其实和 #6 是一样的，但是这个东西会比较复杂，相当于整个更改更新的逻辑，我需要多花点时间来写

**Comment by WingDr** [comment]
> 我觉得你如果还没想到解决方案, 可以先加一个更不更新的开关, 比如我就会把更新关掉😂

我知道怎么改，而且非常明确。加开关这件事在程序上也不简单（尤其是要适配多语言还有readme），不如多等等，我弄好了会及时更新的

**Comment by wangfh5** [comment]
好的, 大佬辛苦了
