### ISSUE TITLE
更新到最新版之后无法跳转zotero窗口

### ISSUE THREAD

**Issue by wangfh5** [WingDr/siyuan-plugin-citation#16]
更新到最新版0.009之后，不管是`alt+shift+P`复制文献引用，还是/add之后插入文献引用，都没有任何反应，不会跳转到zotero，也没有提示zotero未打开（实际上已经打开且Better Bibtex正常运作）
<img width="829" alt="image" src="https://github.com/WingDr/siyuan-plugin-citation/assets/51868839/8048a3a8-6c71-4fcf-89b8-37b37f6dc389">

**Comment by WingDr** [comment]
抱歉，我在推0.0.9的时候忘记删除一个测试的未来功能（就是用debug-bridge插件访问zotero的），所以可能导致卡死了，我现在在推0.1.0，更新后看看还有没有这个问题
