### ISSUE TITLE
使用反馈与建议

### ISSUE THREAD

**Issue by yanyu2015** [WingDr/siyuan-plugin-citation#17]
- 在模板中使用`Journal:	{{publisher}}`，并不能导出期刊，换其他的字段，如publication换大大小写都不行，是我操作不当还是有bug？
- 目前使用zotero的方式，可以生成files（文献对应PDF）的链接，但使用CSL不行的，这是本来就不行么？
- 目前使用zotero的方式，可以生成note和链接，那么，是不是做在PDF中的annotation，要先加入到条目的note中，才能跳转到对应的PDF的位置呢？
- 目前使用zotero的方式，在输入搜索的时候，感觉跳出来的备选文献匹配没有CSL模式的精准（就是你搜关键字，排最前面的文献不是最匹配的），搜索框似乎没有CSL的丝滑（偶尔需要切换到zotero中才能点到搜索框）。另外搜索框的备选可不能显示在文字的下方，目前感觉有遮挡
- 请问能不能给插入文献或笔记添加一个快捷键设置选项呢？
- 最后，感谢开发者！

**Comment by WingDr** [comment]
> 在模板中使用Journal:	{{publisher}}，并不能导出期刊，换其他的字段，如publication换大大小写都不行，是我操作不当还是有bug？

期刊/会议名称的字段应该是{{containerTitle}}，{{publisher}}仅仅是书籍的出版商

> 目前使用zotero的方式，可以生成files（文献对应PDF）的链接，但使用CSL不行的，这是本来就不行么？

对，CSL本身不带有这个字段，所以还是比较建议用bibtex，或者直接对接zotero

> 目前使用zotero的方式，可以生成note和链接，那么，是不是做在PDF中的annotation，要先加入到条目的note中，才能跳转到对应的PDF的位置呢？

目前是的，但是在之后使用debug-bridge的方法中，应该能做到直接提取annotation，这一点我也在尝试

> 目前使用zotero的方式，在输入搜索的时候，感觉跳出来的备选文献匹配没有CSL模式的精准（就是你搜关键字，排最前面的文献不是最匹配的），搜索框似乎没有CSL的丝滑（偶尔需要切换到zotero中才能点到搜索框）。另外搜索框的备选可不能显示在文字的下方，目前感觉有遮挡

CSL的搜索框是我自己写的，zotero的搜索框是它自带的（我还挺高兴有人更欣赏我做的搜索框hhhh非常感谢），之后使用debug-bridge的方法就能用我写的搜索框直接搜索zotero库里的东西了。遮挡的问题是zotero自带的，我也没啥办法orz我自己用也这样

> 请问能不能给插入文献或笔记添加一个快捷键设置选项呢？

因为思源的API限制，在快捷键操作下我没办法插入内容（参见这个[思源issue](https://github.com/siyuan-note/siyuan/issues/8657)），所以我做了一个复制引用的命令，这个是可以在思源的快捷键设置里面设定快捷键的（我没有默认添加快捷键），命令面板里面也可以直接用，执行之后会把除了插入以外的工作都完成，然后把引用链接添加到你的剪贴板，粘贴一下就能放到笔记里。复制笔记我之后也加一下，主要是当时太忙了没做。

**Comment by yanyu2015** [comment]
感谢详尽解答！ {{containerTitle}} 这个字段也不能正常显示期刊名

**Comment by WingDr** [comment]
> 感谢详尽解答！ {{containerTitle}} 这个字段也不能正常显示期刊名

抱歉，这个是我的问题，代码里有的一条下划线打成两条了orz（弱智错误.jpg）下个版本就会修复
