### ISSUE TITLE
插入文献引用的问题和疑问

### ISSUE THREAD

**Issue by wangfh5** [WingDr/siyuan-plugin-citation#19]
1. 最近使用 Better bibtex 模式总是无法插入文献引用，弹出zotero窗口，点击要引用的文献，然后点击确定，就会突然跳到zotero应用程序之中，Siyuan里面则没有效果。

https://github.com/WingDr/siyuan-plugin-citation/assets/51868839/ae19a3eb-ea54-4faf-877d-c599e47b4b2c

2. 使用 debug-bridge 模式只能搜索不能弹出zotero窗口来选择文献吗？
3. debug-bridge 模式的搜索过程中，如果使用中文输入法输英文，按回车本来是为了输入一个候选框没有的单词，结果却被搜索框直接捕获了回车。不知道能不能优化一下。

**Comment by WingDr** [comment]
> 1. 最近使用 Better bibtex 模式总是无法插入文献引用，弹出zotero窗口，点击要引用的文献，然后点击确定，就会突然跳到zotero应用程序之中，Siyuan里面则没有效果。

emmm这个地方的代码我应该没动过，我回去看看能不能复现

> 2. 使用 debug-bridge 模式只能搜索不能弹出zotero窗口来选择文献吗？

对的，作为代替，debug-bridge插件会提供直接插入在zotero中选中的文献这个功能，之后我也会探索怎么弹出zotero的窗口，除了bbt和word插件以外能调用这个东西的zotero插件，如果发现了也请提醒我

> 3. debug-bridge 模式的搜索过程中，如果使用中文输入法输英文，按回车本来是为了输入一个候选框没有的单词，结果却被搜索框直接捕获了回车。不知道能不能优化一下。

我看看能不能解决，之前我一直没这么干都没发现orz

**Comment by wangfh5** [comment]
> 1. emmm这个地方的代码我应该没动过，我回去看看能不能复现
如果不能复现，可能是因为 Better BibTeX 对 zotero 7 beta 的支持还在进行中，可能会有一些bug。

> 2. 我看看能不能解决，之前我一直没这么干都没发现orz
随口插一句，这个问题在很多地方都会遇到，在早些版本的Github Copilot Chat 会出现，还有现在的安卓端微信的输入框。。。

**Comment by WingDr** [comment]
> 如果不能复现，可能是因为 Better BibTeX 对 zotero 7 beta 的支持还在进行中，可能会有一些bug。

啊？你咋能用bbt的，我在zotero7上装最新支持的bbt（作者发在issue里的）都没反应（悲）。不过在zotero 7上这个问题有人找我反应过了，只能说暂时先别用吧，等7正式发或者bbt稳定了我再去看看适配。

> 随口插一句，这个问题在很多地方都会遇到，在早些版本的Github Copilot Chat 会出现，还有现在的安卓端微信的输入框。。。

懂了，感谢提醒，其实主要问题是想要回车输入就必须要绑定keydown，但是中文输入法的这个回车也被绑定了，新版的HTML没有在key这个字段给这两种作区分（安卓的xml也没有），但是说keyCode是不一样的。我去试试看吧，这点确实很影响体验

**Comment by WingDr** [comment]
> debug-bridge 模式的搜索过程中，如果使用中文输入法输英文，按回车本来是为了输入一个候选框没有的单词，结果却被搜索框直接捕获了回车。不知道能不能优化一下。

不对啊，我这复现不出来，我看中文输入法的key和普通回车的key是不一样的，理论上最开始的界面就没问题。你能跟我说一下你是用的是哪种输入法吗？

**Comment by wangfh5** [comment]
macos，搜狗输入法

**Comment by WingDr** [comment]
> macos，搜狗输入法

解决了，是mac系统的问题，下个版本更新再看看

**Comment by SkysCrystal** [comment]
我今天也没法插入文献到思源笔记了，使用 /add 命令，引用选完后笔记内没有出现引用条目，References 也没有创建新页面。昨天用还是可以的，使用的是 Zotero(better-bibtex) 选项。

**Comment by WingDr** [comment]
> 我今天也没法插入文献到思源笔记了，使用 /add 命令，引用选完后笔记内没有出现引用条目，References 也没有创建新页面。昨天用还是可以的，windows 系统使用的是 Zotero(better-bibtex) 选项，软件、插件都检查更新到最新版本了。

应该就是和bbt的通信出问题了，我现在用zotero 7 和最新的bbt没法复现这个情况，可以等我这两天更新试试新版本还有没有这个问题。另外，现在使用debug-bridge的方法是明确可以支持zotero 7的（而且很稳定），如果不是习惯经典视图选择文献的推荐一试

**Comment by SkysCrystal** [comment]
> 

感谢回复！我更换 zotero 的 debug-bridge 插件并做设置后，可以使用了。【我的 zotero 是 6.0.26】

![我的截图](https://github.com/WingDr/siyuan-plugin-citation/assets/49473463/25fdd1b2-dc0d-4ff7-b284-a790a89a089f)
我的命令面板中没有出现下图的文献引用选项。
![commandpanel](https://github.com/WingDr/siyuan-plugin-citation/raw/main/assets/commandpanel.png)

**Comment by WingDr** [comment]
> > 
> 
> 感谢回复！我更换 zotero 的 debug-bridge 插件并做设置后，可以使用了。【我的 zotero 是 6.0.26】
> 
> ![我的截图](https://user-images.githubusercontent.com/49473463/258426133-25fdd1b2-dc0d-4ff7-b284-a790a89a089f.png) 我的命令面板中没有出现下图的文献引用选项。 ![commandpanel](https://github.com/WingDr/siyuan-plugin-citation/raw/main/assets/commandpanel.png)

命令这个问题由来已久……是不是设置里面快捷键那个页面都空白了？可以关闭插件再打开看下，我感觉是因为思源本体没有处理多个插件初始化冲突的问题（所有插件都往命令那个列表塞东西的时候冲突了）

**Comment by SkysCrystal** [comment]
> 命令这个问题由来已久……是不是设置里面快捷键那个页面都空白了？可以关闭插件再打开看下，我感觉是因为思源本体没有处理多个插件初始化冲突的问题（所有插件都往命令那个列表塞东西的时候冲突了）

啊确实……快捷键页面也白了

**Comment by WingDr** [comment]
> 啊确实……快捷键页面也白了

嗯嗯，遇到这种情况在设置->集市里面关闭再打开citation插件一般就好了，暂时也只能这样了
