### ISSUE TITLE
文献库路径不存在

### ISSUE THREAD

**Issue by yanyu2015** [WingDr/siyuan-plugin-citation#2]
在思源的\data\plugins\siyuan-plugin-citation下，创建了References文件夹，存放了better bib导出的My Library.bib和My Library.json（确认了里面有文献数据）
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/11142054/343e144d-84a2-49fe-a491-9de1e9163208)
插件面板设置如上，但/add的时候提示文献库路径不存在，请问是什么原因？

**Comment by WingDr** [comment]
文献库路径不存在的问题是因为你的笔记本SYnote中没有/References，以'/'开头是指笔记本的根目录，文献库指的是文献的内容在思源笔记本中的储存路径，所以在思源的文档树里直接新建References文档就可以。

此外，因为在plugin文件夹储存数据不安全（参考相关issue #1 ），所以在v0.0.3版以后存放.bib和.json的文件夹改成了`[工作空间]/data/storage/petal/siyuan-plugin-citation/references/`，请将文件放到新的储存路径并及时更新最新版本的插件。

目前还在努力开发功能，所以文档和UI提示暂时还不完善，请见谅

**Comment by yanyu2015** [comment]
感谢
```
data\storage\petal\siyuan-plugin-citation\references
```
这个路径是对的。
我之前配成这个了
```
\data\plugins\siyuan-plugin-citation
```
换成第一个就ok了！

**Comment by zwb709213019** [comment]
想问下如果数据库类型选择zotero的话，是不是也要配置好文献库路径呢？
![图片](https://github.com/WingDr/siyuan-plugin-citation/assets/20367302/40031e4c-785c-44d0-b197-477821227251)
如果不需要的话，在笔记中输入`/add`并选择后，还是会提醒文献库路径不存在。
![图片](https://github.com/WingDr/siyuan-plugin-citation/assets/20367302/d48ac231-50cd-4c68-bc6b-c75dc8776899)
而且将数据库类型改回 BibTex and CSL-JSON ，还是会提醒文献库路径不存在。我这边也在 `[工作空间]/` 中新建 references 文件夹了，里面放了一个 .json 文件准备测试来着。
![图片](https://github.com/WingDr/siyuan-plugin-citation/assets/20367302/0ade8ec8-a68c-4a7c-a21b-ce2dafa2f8ab)
![图片](https://github.com/WingDr/siyuan-plugin-citation/assets/20367302/a9211de8-c37d-4e6c-9fde-648fcf74fe85)
![图片](https://github.com/WingDr/siyuan-plugin-citation/assets/20367302/635993fc-438a-43c8-b370-8c3945ca16b9)

**Comment by Geo123abc** [comment]
> 想问下如果数据库类型选择zotero的话，是不是也要配置好文献库路径呢？ ![图片](https://user-images.githubusercontent.com/20367302/251508672-40031e4c-785c-44d0-b197-477821227251.png) 如果不需要的话，在笔记中输入`/add`并选择后，还是会提醒文献库路径不存在。 ![图片](https://user-images.githubusercontent.com/20367302/251508751-d48ac231-50cd-4c68-bc6b-c75dc8776899.png) 而且将数据库类型改回 BibTex and CSL-JSON ，还是会提醒文献库路径不存在。我这边也在 `[工作空间]/` 中新建 references 文件夹了，里面放了一个 .json 文件准备测试来着。 ![图片](https://user-images.githubusercontent.com/20367302/251508878-0ade8ec8-a68c-4a7c-a21b-ce2dafa2f8ab.png) ![图片](https://user-images.githubusercontent.com/20367302/251508930-a9211de8-c37d-4e6c-9fde-648fcf74fe85.png) ![图片](https://user-images.githubusercontent.com/20367302/251509168-635993fc-438a-43c8-b370-8c3945ca16b9.png)

我也是报这个错，不知道咋设置，“文献库路径”那个参数有点迷，希望作者可以直接举个实例，比如选择不同数据库类型时，文献库路径怎么设置，这样像我这种小白直接模仿抄作业就好了，期待。

**Comment by yanyu2015** [comment]
楼上两位，仔细看，选择zotero后，要在你的笔记本下创建References笔记（是在思源笔记软件中创建，而不是在文件夹中，比如你们选择的都是科研笔记本，就要在科研笔记本中点那个加号，新建一个名为References的笔记）。然后你们配置的references路径似乎也不对，仔细看我上面写的路径，不是直接在siyuan根目录下，是在data\storage\petal\siyuan-plugin-citation下

**Comment by WingDr** [comment]
> 想问下如果数据库类型选择zotero的话，是不是也要配置好文献库路径呢？ ![图片](https://user-images.githubusercontent.com/20367302/251508672-40031e4c-785c-44d0-b197-477821227251.png) 如果不需要的话，在笔记中输入`/add`并选择后，还是会提醒文献库路径不存在。 ![图片](https://user-images.githubusercontent.com/20367302/251508751-d48ac231-50cd-4c68-bc6b-c75dc8776899.png) 而且将数据库类型改回 BibTex and CSL-JSON ，还是会提醒文献库路径不存在。我这边也在 `[工作空间]/` 中新建 references 文件夹了，里面放了一个 .json 文件准备测试来着。 ![图片](https://user-images.githubusercontent.com/20367302/251508878-0ade8ec8-a68c-4a7c-a21b-ce2dafa2f8ab.png) ![图片](https://user-images.githubusercontent.com/20367302/251508930-a9211de8-c37d-4e6c-9fde-648fcf74fe85.png) ![图片](https://user-images.githubusercontent.com/20367302/251509168-635993fc-438a-43c8-b370-8c3945ca16b9.png)

文献库是在思源笔记里你选择的笔记本中存放文献内容的路径，是在文档树中创建这个路径。如果你直接用zotero的话是不需要放.bib文件到实际的文件夹的。

下个版本我把README和这个设置界面的说明更新一下

**Comment by WingDr** [comment]
> > 想问下如果数据库类型选择zotero的话，是不是也要配置好文献库路径呢？ ![图片](https://user-images.githubusercontent.com/20367302/251508672-40031e4c-785c-44d0-b197-477821227251.png) 如果不需要的话，在笔记中输入`/add`并选择后，还是会提醒文献库路径不存在。 ![图片](https://user-images.githubusercontent.com/20367302/251508751-d48ac231-50cd-4c68-bc6b-c75dc8776899.png) 而且将数据库类型改回 BibTex and CSL-JSON ，还是会提醒文献库路径不存在。我这边也在 `[工作空间]/` 中新建 references 文件夹了，里面放了一个 .json 文件准备测试来着。 ![图片](https://user-images.githubusercontent.com/20367302/251508878-0ade8ec8-a68c-4a7c-a21b-ce2dafa2f8ab.png) ![图片](https://user-images.githubusercontent.com/20367302/251508930-a9211de8-c37d-4e6c-9fde-648fcf74fe85.png) ![图片](https://user-images.githubusercontent.com/20367302/251509168-635993fc-438a-43c8-b370-8c3945ca16b9.png)
> 
> 我也是报这个错，不知道咋设置，“文献库路径”那个参数有点迷，希望作者可以直接举个实例，比如选择不同数据库类型时，文献库路径怎么设置，这样像我这种小白直接模仿抄作业就好了，期待。

好的，下个版本我会更新一下README和设置界面的说明

**Comment by zwb709213019** [comment]
> 楼上两位，仔细看，选择zotero后，要在你的笔记本下创建References笔记（是在思源笔记软件中创建，而不是在文件夹中，比如你们选择的都是科研笔记本，就要在科研笔记本中点那个加号，新建一个名为References的笔记）。然后你们配置的references路径似乎也不对，仔细看我上面写的路径，不是直接在siyuan根目录下，是在data\storage\petal\siyuan-plugin-citation下

谢谢回复！在《科研》笔记本下面创建《References》笔记后，确实解决“文献库路径不存在！”这一问题了。不过有新的问题，就是提示“Zotero没有运行”，
![图片](https://github.com/WingDr/siyuan-plugin-citation/assets/20367302/fee9d204-ccac-4c27-8b6b-ccc7aaac5cb5)
但我已经打开Zotero了，想问下是不是对Zotero的版本或者配置有一定要求咧？
![图片](https://github.com/WingDr/siyuan-plugin-citation/assets/20367302/3bea02ce-7d8e-4f73-bc1d-849480c8aa34)

**Comment by WingDr** [comment]
> 谢谢回复！在《科研》笔记本下面创建《References》笔记后，确实解决“文献库路径不存在！”这一问题了。不过有新的问题，就是提示“Zotero没有运行”， ![图片](https://user-images.githubusercontent.com/20367302/251610423-fee9d204-ccac-4c27-8b6b-ccc7aaac5cb5.png) 但我已经打开Zotero了，想问下是不是对Zotero的版本或者配置有一定要求咧？ ![图片](https://user-images.githubusercontent.com/20367302/251610553-3bea02ce-7d8e-4f73-bc1d-849480c8aa34.png)

这个原因可能比较复杂，请问你的zotero中是否安装了Better BibTex插件？如果已经安装的话，能否请你在设置里关闭插件再打开试试看？

**Comment by zwb709213019** [comment]
> > 谢谢回复！在《科研》笔记本下面创建《References》笔记后，确实解决“文献库路径不存在！”这一问题了。不过有新的问题，就是提示“Zotero没有运行”， ![图片](https://user-images.githubusercontent.com/20367302/251610423-fee9d204-ccac-4c27-8b6b-ccc7aaac5cb5.png) 但我已经打开Zotero了，想问下是不是对Zotero的版本或者配置有一定要求咧？ ![图片](https://user-images.githubusercontent.com/20367302/251610553-3bea02ce-7d8e-4f73-bc1d-849480c8aa34.png)
> 
> 这个原因可能比较复杂，请问你的zotero中是否安装了Better BibTex插件？如果已经安装的话，能否请你在设置里关闭插件再打开试试看？

您好！我的Zotero没有安装 Better BibTex 插件，而且把其他插件也取消之后，仍然出现 Zotero没有在运行 的提示。
![图片](https://github.com/WingDr/siyuan-plugin-citation/assets/20367302/dbe51302-d407-4838-8f90-d1ae7c5e7fdf)

**Comment by WingDr** [comment]
> 您好！我的Zotero没有安装 Better BibTex 插件，而且把其他插件也取消之后，仍然出现 Zotero没有在运行 的提示。 ![图片](https://user-images.githubusercontent.com/20367302/251634828-dbe51302-d407-4838-8f90-d1ae7c5e7fdf.png)

不好意思，我的意思是这个插件的运行是依赖于Zotero的[Better BibTex插件](https://github.com/retorquere/zotero-better-bibtex)的，因为zotero本身没有提供很方便的外部接口功能，借助Better BibTex提供的接口本插件才能运行（参考[JSON-RPC of better-bibtex](https://retorque.re/zotero-better-bibtex/exporting/json-rpc/)），所以请你安装一下这个插件然后再尝试运行，这一点我也会在新版本中加入说明（主要是我平常的环境里直接就有所以没意识到这一点orz）

**Comment by Junbin6** [comment]
我也遇到了楼上的各个问题，按照提示做了还是有问题。不过重启思源就好了。建议作者在介绍里加一下“更改设置后，重启生效”之类的提示。（我是mac，不知道win是不是一样的）

**Comment by Geo123abc** [comment]
> 我也遇到了楼上的各个问题，按照提示做了还是有问题。不过重启思源就好了。建议作者在介绍里加一下“更改设置后，重启生效”之类的提示。（我是mac，不知道win是不是一样的）

请问，mac在设置  文献库路径时，是左斜杠 /  ？  还是右斜杠 \  ？

**Comment by WingDr** [comment]
> 我也遇到了楼上的各个问题，按照提示做了还是有问题。不过重启思源就好了。建议作者在介绍里加一下“更改设置后，重启生效”之类的提示。（我是mac，不知道win是不是一样的）

重启这个挺奇怪的，可能是内部某些逻辑的问题，感谢提醒，在README里面我会加上

**Comment by Junbin6** [comment]
> > 我也遇到了楼上的各个问题，按照提示做了还是有问题。不过重启思源就好了。建议作者在介绍里加一下“更改设置后，重启生效”之类的提示。（我是mac，不知道win是不是一样的）
> 
> 请问，mac在设置 文献库路径时，是左斜杠 / ？ 还是右斜杠 \ ？

默认的，应该是/（这是插件里的）（思源文件夹里就按照路径直接新建文件夹）
