### ISSUE TITLE
关于文献笔记的模板

### ISSUE THREAD

**Issue by yanyu2015** [WingDr/siyuan-plugin-citation#20]
非常感谢开发者带来的更丝滑的联动方案，看到新版可以插入文献笔记，但测试了下，发现当前的文献笔记插入方式较为简陋，不知能否改进？
- 比如，在使用zotero-pdf-translate插件生成的笔记中，插入后只显示中文，没有对应的原文
- 比如目前似乎不能很好地调整到PDF原文？
- 是否支持插入部分笔记？（zotero自身支持复制后粘贴到思源笔记中，但感觉它生成的字段命名不是很好，跟思源的适配没有跟ob的好）

**Comment by WingDr** [comment]
插件插入的笔记应该就是zotero中的原始笔记，只不过zotero中原始笔记是富文本的形式，所以我得到的只有HTML，所以我不太清楚具体是什么样子的需求？

> 在使用zotero-pdf-translate插件生成的笔记中，插入后只显示中文，没有对应的原文

我看zotero-pdf-translate里面并没有直接生成笔记的方法，请问你的笔记具体是什么样子的？

> 目前似乎不能很好地调整到PDF原文？

本身笔记中有跳转到zotero的链接才能直接跳转到zotero吧，笔记上有一个Locate按钮可以直接跳转到笔记条目。我觉得你的意思是不是想要在pdf中做标注然后从思源直接跳转到pdf标注的地方？这样的话建议用debug-bridge方法中的annotations变量提取pdf的标注，这个东西我是直接做了跳转到pdf原文标注位置的。

> 是否支持插入部分笔记？（zotero自身支持复制后粘贴到思源笔记中，但感觉它生成的字段命名不是很好，跟思源的适配没有跟ob的好）

这里的部分笔记是指？字段命名是？不过我好像确实没有给note做可以自定义条目的东西，如果有需求的话可以一样做一个{{noteList}}出来（像{{fileList}}和{{annotationList}}一样），这样在模板里就可以通过JavaScript代码筛选/修改部分笔记。

**Comment by yanyu2015** [comment]
重新找个新文献测试了下：
- 我之前的理解有问题，重新测试后，发现目前插件实现的插入的笔记，是条目下的note，也就是说，在文档中高亮后，加入note才能插入到思源中，我说的那种其实是annotation，其实是文中的高亮。（zotero复制出来的转义文本支持直接跳转到PDF对应的内容上，但是思源中粘贴转义文本经常失效，我不知道是不是我操作不当？作者方便分享下不？）
- OK，那么就用zotero中的note为例，目前怎么做到note内容修改后的更新呢？重新插入是可以的，但不知道能不能自动更新，以及更新的方向是不是只能从zotero到思源
- 插入笔记生成的`Open`链接，在跳转的时候有bug，请测试下。

**Comment by WingDr** [comment]
> 在文档中高亮后，加入note才能插入到思源中，我说的那种其实是annotation，其实是文中的高亮。

对的，如果是在zotero自带的pdf阅读器打开pdf然后标注的话，是能够被annotations提取的，如果是被外部pdf阅读器标注的话，可能就需要手动提取一下加入note。

> zotero复制出来的转义文本支持直接跳转到PDF对应的内容上，但是思源中粘贴转义文本经常失效，我不知道是不是我操作不当？作者方便分享下不？

我知道你说的是啥了，这个是zotero的富文本编辑器专门支持的格式，你可以看到它在zotero的编辑器中也不是以链接的方式存在的（得点一下再点“在页面显示”才会跳转）。我争取在下个版本琢磨清楚这个东西具体的格式是什么，然后把结尾的引用转换成跳转pdf的链接

> 目前怎么做到note内容修改后的更新呢？重新插入是可以的，但不知道能不能自动更新，以及更新的方向是不是只能从zotero到思源

目前没有做自动更新，就是每次插入的时候会从zotero中提取然后覆盖思源里的内容，还是以zotero为主。之后会开发能手动反向把笔记同步回zotero的功能。自动同步短时间内应该就不考虑了，主要是因为处理冲突这件事情很麻烦，整个半成品出来容易把大家本身整理好的笔记搞乱。

> 插入笔记生成的Open链接，在跳转的时候有bug，请测试下。

哦哦这个是我的问题，这玩意好像是得安装 zotero better note 才能打开，我之前一直没注意到也没人跟我说（主要是我自己一直能用orz），之后我会把它删除，应该Locate本身就够用了

**Comment by WingDr** [comment]
不好意思打扰了，还有一些问题想要问你：

> zotero自身支持复制后粘贴到思源笔记中，但感觉它生成的字段命名不是很好，跟思源的适配没有跟ob的好。
> zotero复制出来的转义文本支持直接跳转到PDF对应的内容上，但是思源中粘贴转义文本经常失效，我不知道是不是我操作不当？作者方便分享下不？

这个我看了一下，是zotero自己复制出来就自带一个链接格式，不知道为什么复制到思源里这个链接就消失了，最离谱的是先复制到文本文档里，再复制到思源里的时候就一切正常，我准备去思源本体提一个issue。

主要问题是如果我对导入之后笔记的地方做识别修改的话，最后反向同步回Zotero的时候可能会有很大的问题，所以我想问一下这种功能是很重要的吗？如果仅使用annotations是否可以？

**Comment by yanyu2015** [comment]
感谢！最近比较忙，没有上线。
>最离谱的是先复制到文本文档里，再复制到思源里的时候就一切正常
太猛了你，我之前也试出来了，但跟几个群友交流他们似乎都没反馈这个问题，我还以为是我操作不对。

其实我觉得，最主要的是以下几点：
- 能够引用到文献，知道是谁的论文，这个目前已经有了
- 论文中中的片段，无论是图片或选中的文字，能够较为方便地复制的思源笔记中，并附带一个自动跳转的链接，无奈目前思源复制annotation有bug，那么即便这个bug修复了，目前也有一定的缺陷，我觉得比较完美的是，文字+显示一个链接（这个链接有作者，年份，期刊，标题+页码，页码其实没啥用，但是页码可以帮助你区分多条笔记，否则全是相同的文献内容），然后最后当一个annotation被思源复制后，可以有一个从思源到zotero的链接贴到zotero中（但这个似乎很难实现，所以也不必尝试）。
- 双向同步我觉得不是很有必要，首先难度太大，其次也不太具备可行性。甚至我觉得目前zotero better note或其他插件给一个笔记创建一个note，然后把annotation加入到note中的方式，如果zotero复制到思源没有bug，其实跟在思源中直接针对单个文献创建一个笔记的做法并不会有太大不同。所以我觉得如果思源修复了这个bug，然后插件能够在做特若自带的基础上自定义以下粘贴后显示的字段内容，我觉得就比较完美了，这样思源就成了较好的文献汇总和摘录工具，倒不必渴求要弄成写文献综述的工具。

**Comment by WingDr** [comment]
来的正好hhhh之前的问题貌似是解决了

> 最离谱的是先复制到文本文档里，再复制到思源里的时候就一切正常

这个我知道为什么了，多亏了 @Geo123abc 给的解答。你看一下Zotero里面 `编辑->设置/首选项->导出` 里面有一个叫“笔记格式”的东西，里面要把“富文本/HTML”的“包括Zotero链接”勾上，就像下面这张图里（我是Zotero 7），才能够直接复制和拖动到思源然后还带链接。因为ob直接是markdown（文本）编辑器所以混淆了，事实上拖到思源里粘贴的是富文本

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/0ae3fbad-0556-4e65-b44d-505bbfc0e995)

> 论文中中的片段，无论是图片或选中的文字，能够较为方便地复制的思源笔记中，并附带一个自动跳转的链接，无奈目前思源复制annotation有bug，那么即便这个bug修复了，目前也有一定的缺陷，我觉得比较完美的是，文字+显示一个链接（这个链接有作者，年份，期刊，标题+页码，页码其实没啥用，但是页码可以帮助你区分多条笔记，否则全是相同的文献内容）

目前的bug就像上面说的那样，看看能不能解决。然后我测试了一下图片的粘贴似乎不太行，没有图片出来（但是复制到word也不行，应该是从zotero那边就有问题的）。至于你说的链接有作者、年份之类的，我等目前的东西开发完去问问D大能不能开放一个drop（从外面拖东西进来）或者paste（从外面粘贴东西进来）的触发，这样的话随着拖动和粘贴就能直接添加引用，也相当于变相满足这个需求了。

> 最后当一个annotation被思源复制后，可以有一个从思源到zotero的链接贴到zotero中（但这个似乎很难实现，所以也不必尝试）。

这个在添加引用里已经做出来了，只要使用debug-bridge插件就能在插入引用的时候在zotero的对应条目里添加一个思源的反链，指向文献库里的对应文档，然后如果上面说的那个实现了，就能通过文档的被引用找到笔记添加的位置。

> 双向同步我觉得不是很有必要，首先难度太大，其次也不太具备可行性。甚至我觉得目前zotero better note或其他插件给一个笔记创建一个note，然后把annotation加入到note中的方式，如果zotero复制到思源没有bug，其实跟在思源中直接针对单个文献创建一个笔记的做法并不会有太大不同。所以我觉得如果思源修复了这个bug，然后插件能够在做特若自带的基础上自定义以下粘贴后显示的字段内容，我觉得就比较完美了，这样思源就成了较好的文献汇总和摘录工具，倒不必渴求要弄成写文献综述的工具。

ok，双向同步目前确实难度很大，但是如果思源的自定义块出来，我就能把笔记的那些地方全都改成和zotero里面一样的富文本编辑块，这样的话反向同步就非常简单了（但是应该要很久以后）。

**Comment by yanyu2015** [comment]
感谢
- 目前zotero复制出来是 “作者，年份，页码和PDF”，但实际上“作者，年份，页码”跳转的的是条目，PDF跳转到的是“具体的页码”，感觉是做特若自己的问题，所以这个不知道插件能不能改或者直接改zotero的模板？
- >这个在添加引用里已经做出来了，只要使用debug-bridge插件就能在插入引用的时候在zotero的对应条目里添加一个思源的反链，指向文献库里的对应文档，然后如果上面说的那个实现了，就能通过文档的被引用找到笔记添加的位置。
 
这个暂时没get到，是指能在zotero链接中添加一个反链到思源么？
- 另外，我对zotero better note的使用不熟悉，感觉添加annotation后要手动添加到note中，有点麻烦，不知道他是不是支持自动把所有的annotation抽取到某个note中并自动更新。

**Comment by WingDr** [comment]
> 目前zotero复制出来是 “作者，年份，页码和PDF”，但实际上“作者，年份，页码”跳转的的是条目，PDF跳转到的是“具体的页码”，感觉是做特若自己的问题，所以这个不知道插件能不能改或者直接改zotero的模板？

这个是zotero自己给的，改不了，但是像之前说如果思源开了拖拽和复制的API那就可以在思源里操作粘贴的内容了

> 这个暂时没get到，是指能在zotero链接中添加一个反链到思源么？

对，在zotero的对应条目下添加一个链接的附件，这个链接是指向思源的，双击这个附件就可以直接跳转到思源

> 另外，我对zotero better note的使用不熟悉，感觉添加annotation后要手动添加到note中，有点麻烦，不知道他是不是支持自动把所有的annotation抽取到某个note中并自动更新。

这个貌似是better note的作者没做，也没办法orz为啥不直接尝试插件模板里的{{annotations}}？应该跟better note提取的效果差不多？

**Comment by Geo123abc** [comment]
> > 目前zotero复制出来是 “作者，年份，页码和PDF”，但实际上“作者，年份，页码”跳转的的是条目，PDF跳转到的是“具体的页码”，感觉是做特若自己的问题，所以这个不知道插件能不能改或者直接改zotero的模板？
> 
> 这个是zotero自己给的，改不了，但是像之前说如果思源开了拖拽和复制的API那就可以在思源里操作粘贴的内容了
> 
> > 这个暂时没get到，是指能在zotero链接中添加一个反链到思源么？
> 
> 对，在zotero的对应条目下添加一个链接的附件，这个链接是指向思源的，双击这个附件就可以直接跳转到思源
> 
> > 另外，我对zotero better note的使用不熟悉，感觉添加annotation后要手动添加到note中，有点麻烦，不知道他是不是支持自动把所有的annotation抽取到某个note中并自动更新。
> 
> 这个貌似是better note的作者没做，也没办法orz为啥不直接尝试插件模板里的{{annotations}}？应该跟better note提取的效果差不多？

yanyu2015 说的“在zotero链接中添加一个反链到思源”可能是拖拽的块思源ID到zotero子条目、或者PDF页面，以方便点击这个链接就能到思源笔记的块中，并且你说的citation下面这个功能还没release：
>这个在添加引用里已经做出来了，只要使用debug-bridge插件就能在插入引用的时候在zotero的对应条目里添加一个思源的反链，指向文献库里的对应文档，然后如果上面说的那个实现了，就能通过文档的被引用找到笔记添加的位置。



@yanyu2015 
> 我对zotero better note的使用不熟悉，感觉添加annotation后要手动添加到note中，有点麻烦，不知道他是不是支持自动把所有的annotation抽取到某个note中并自动更新。

这个可以通过在父条目上右键“通过注释添加笔记”把PDF中的annotations提取到一个子note中（zotero6某个版本之后的功能），如果你说的“所有的annotation”指的是整个文献库的annotations,那我就不知道了。

**Comment by WingDr** [comment]
v0.2.0已经支持从Zotero直接拖拽选中区域/批注（复制批注也可以）的时候自动将Zotero的链接替换为citation插件的引用。笔记的问题可以等我再研究研究，这个issue先关了
