### ISSUE TITLE
关于Quicker，后续插件会非常依赖Quicker吗？

### ISSUE THREAD

**Issue by Junbin6** [WingDr/siyuan-plugin-citation#22]
我是MAC用户，目前的插件版本基本已经满足日常使用了。如果后续新的功能依赖Quicker，是否会影响MAC用户？

**Comment by WingDr** [comment]
> 我是MAC用户，目前的插件版本基本已经满足日常使用了。如果后续新的功能依赖Quicker，是否会影响MAC用户？

我没有开发依赖Quicker的功能的想法，我自己也不使用Quicker（用不惯），所以我肯定会保证单纯使用这个插件的用户的体验（起码是保证我自己的使用体验）的

当然某些特性上可能会适配一些Quicker使用的需求，但是一方面我会尽力做到改变不让用户感知，另一方面插件本身的绝大部分功能（最起码主要的功能）一定是不会依赖Quicker的

使用mac的话，有bug欢迎来提issue，我这没有苹果的测试设备，不知道后端平台变化会不会导致一些问题
