### ISSUE TITLE
DOI或者URL能否默认设置为超链接

### ISSUE THREAD

**Issue by Junbin6** [WingDr/siyuan-plugin-citation#23]
版本0.1.4
目前插入的DOI和URL是不带链接的，虽然可以拷贝粘贴，但是更希望他们可以直接点击。

**Comment by WingDr** [comment]
> 版本0.1.4 目前插入的DOI和URL是不带链接的，虽然可以拷贝粘贴，但是更希望他们可以直接点击。

如果想要直接点击的话，可以在模板里面操作？试试

```markdown
{{ `[${DOI}](${DOI})` }}
和
{{ `[${URL}](${URL})` }} 
```

主要是有的人可能不想看到链接本身，只想看到固定的锚文本，那么直接给出链接格式就不太好了，不如把这些都留给用户自定义

如果你不知道怎么把上面这个加进模板，可以把现在的模板包含这两个的部分发到这里我帮你改一下

**Comment by Junbin6** [comment]
OK了，谢谢～
