### ISSUE TITLE
建议文献内容的属性，命名字段可以自定义模板

### ISSUE THREAD

**Issue by HoollyFox** [WingDr/siyuan-plugin-citation#24]
感谢开发者提供的如此舒服的插件，以下是一点小小的意见:

现在文献内容的属性面板内，“命名” 字段是设置为 key，这一设置有一个问题是，如果我使用的是 SiYuan 自带的引用，那么动态锚文本就会自动显示“命名” 字段，只能手动设置静态锚文本，也不方便以后动态更新锚文本。

建议: 

把 key 字段挪到其他属性，比如自定义属性里面，然后命名字段可以和[引用链接](https://github.com/WingDr/siyuan-plugin-citation/blob/main/README_zh_CN.md#%E5%90%8D%E8%AF%8D%E8%AF%B4%E6%98%8E)模板一样设置，或者留空。

甚至可以取消引用链接模板，只提供”命名“字段模板，以实现动态锚文本随命名字段修改，如果需要静态锚文本则用户手动设置。

这样做的好处是:

1. 在不需要更新文献内容的时候，可以使用思源笔记自带的引用功能。
2. 实现自定义动态锚文本。
3. "命名"可以和思源笔记的虚拟引用互动，实现知识发现和自动索引。
4. 更自由的属性管理，适配之后的属性面板。

**Comment by WingDr** [comment]
感谢你的建议

> 把 key 字段挪到其他属性，比如自定义属性里面，然后命名字段可以和[引用链接](https://github.com/WingDr/siyuan-plugin-citation/blob/main/README_zh_CN.md#%E5%90%8D%E8%AF%8D%E8%AF%B4%E6%98%8E)模板一样设置，或者留空。
> 
> 甚至可以取消引用链接模板，只提供”命名“字段模板，以实现动态锚文本随命名字段修改，如果需要静态锚文本则用户手动设置。

在之后我会把 key 放在自定义属性（应该就叫“literature-key”了）上，然后提供“使用动态锚文本作为引用链接”的开关，如果打开了那么就在插入/刷新标题的同时把命名改成引用链接的形式（链接本身会变成锚文本为空的动态锚文本链接）

但是静态锚文本还是要提供的，一方面是静态锚文本本身比动态锚文本要稳定，动态锚文本的更新本身有一定的缺陷（比如下图中说到的），另一方面是之后如果思源支持了引用链接的自定义属性，锚文本是可以在不同形式间变化的（类似LATEX中的\citet和\citep），这一点如果是动态锚文本就做不到

![04b10b5fab8f4eaf274e50988297d2f9](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/cd640e4e-ada1-4e18-8c84-3840cbfa33da)

> 如果我使用的是 SiYuan 自带的引用，那么动态锚文本就会自动显示“命名” 字段，只能手动设置静态锚文本，也不方便以后动态更新锚文本。

关于这一点，如你所见entry-data里面已经有所有导入文献的数据了，我之后想要做的就是在不开启zotero的情况下直接用思源本地的数据进行文献的引用（这也是让插件能在移动端使用的基础），到时候想要直接引用就不需要复制块引然后改锚文本了

**Comment by HoollyFox** [comment]
感谢，持续关注，谢谢您！

**Comment by WingDr** [comment]
v0.2.0已经支持动态锚文本的引用链接，请谨慎使用
