### ISSUE TITLE
titleShort 字段失效

### ISSUE THREAD

**Issue by HoollyFox** [WingDr/siyuan-plugin-citation#25]
无论是标题还是文献内容里面，使用 {{titleShort}} 均无法显示，已经确认文献里有这个字段，在 entry-data 里面也有这一项，但是字段名字为: shortTitle， 我使用这一字段依旧无法显示。

**Comment by WingDr** [comment]
> 无论是标题还是文献内容里面，使用 {{titleShort}} 均无法显示，已经确认文献里有这个字段，在 entry-data 里面也有这一项，但是字段名字为: shortTitle， 我使用这一字段依旧无法显示。

我看到了，这个是我处理数据的问题，下个版本更正，如果着急用的话可以直接用{{entry.data.shortTitle}}（这个之后也不会变）

**Comment by HoollyFox** [comment]
好的，感谢！
