### ISSUE TITLE
已有的 zotero link 在列表中会被错误解析导致错误

### ISSUE THREAD

**Issue by HoollyFox** [WingDr/siyuan-plugin-citation#27]
见视频

https://github.com/WingDr/siyuan-plugin-citation/assets/23378900/fb5f5833-f5f4-49fa-a66a-beabfeb88209

这一问题只有插件[citation](https://github.com/WingDr/siyuan-plugin-citation)打开的时候会出现。

猜测是插件会监控输入行为，如果有zotero://select/开头的 url link 出现时会自动解析并替换成 SiYuan 的引用块格式。

通常这样监控不会出问题，但是如果我过去的文本（指安装插件[citation](https://github.com/WingDr/siyuan-plugin-citation)之前）已经有zotero://select/开头的文本时，解析和替换应该和 SiYuan 笔记相关机制冲突了。

此问题导致的文段消失无法撤销（会报错），应该是较大问题的 bug 了。

暂时的解决办法是，手动替换所有的已有的zotero://select/ link。

以下是可以实验的输入文本，zotero link自行替换自己 zotero 库里面有的文献，

```
* 2022-11-17 change points detection in spatial data

  * [[(Otto and Steinert 2022)](zotero://select/library/items/K6YJL8CM)](zotero://select/library/items/K6YJL8CM)
* 2022-11-28 conformal prediction in missing data problem
```

**Comment by HoollyFox** [comment]
此问题导致的文段消失无法还原，应该是较大问题的 bug 了。

**Comment by WingDr** [comment]
这个替换是因为触发了从zotero粘贴过来批注的那个功能（思源自己这里触发和从外面粘贴没有任何区别，很无语）

出现你这个问题是因为列表的修改返回的是整个列表的id，一下子更新更新整个列表思源的索引就会崩。我改了一下在更新的时候会尽量获得最小范围的块进行更新，目前你给的这个例子（列表）和表格我测试了一下没问题（不知道还有没有其他的问题orz）

我马上更新一版修复这个问题，周末会推送一个能够设定取消这个功能

如果更新之后有这个问题，直接在这个下面说，周末更新之前我都会开着

**Comment by HoollyFox** [comment]
> 这个替换是因为触发了从zotero粘贴过来批注的那个功能（思源自己这里触发和从外面粘贴没有任何区别，很无语）
> 
> 出现你这个问题是因为列表的修改返回的是整个列表的id，一下子更新更新整个列表思源的索引就会崩。我改了一下在更新的时候会尽量获得最小范围的块进行更新，目前你给的这个例子（列表）和表格我测试了一下没问题（不知道还有没有其他的问题orz）
> 
> 我马上更新一版修复这个问题，周末会推送一个能够设定取消这个功能
> 
> 如果更新之后有这个问题，直接在这个下面说，周末更新之前我都会开着

好的，持续关注，谢谢你！

**Comment by WingDr** [comment]
v0.2.3已添加开关
