### ISSUE TITLE
pdf 文件名包含英文括号时的 `{{files}}` 解析结果链接被文件名的括号中断，导致链接无法正确渲染

### ISSUE THREAD

**Issue by XinLi0111** [WingDr/siyuan-plugin-citation#28]
`[Wang et al. - 2023 - Two (TTTTT.pdf](file://D:\Zotero\ZoteroData\storage\563HVZRV\Wang et al. - 2023 - Two (TTTTT.pdf)`

将两个左括号删除后即可正常渲染。

**Comment by WingDr** [comment]
感谢提醒，这个是markdown链接的识别格式问题，下个版本修复

**Comment by WingDr** [comment]
v0.2.3已修复，检查一下

**Comment by XinLi0111** [comment]
还是存在问题
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/31495943/b93cb748-69b0-4718-8ce9-7bdb7f3606c8)

**Comment by WingDr** [comment]
> 还是存在问题

我试了一下，确实是有问题……但是如果你在链接后面打一下空格就会生成链接，然后会自己新建一个文档。这个是思源的链接解析问题，我去那边提个issue
