### ISSUE TITLE
建议“引用模板”引入变量`{{siyuaninnerlink}}`：插入参考文献不能只考虑“入”，还要考虑“出”

### ISSUE THREAD

**Issue by Geo123abc** [WingDr/siyuan-plugin-citation#3]
### 建议“引用模板”引入变量`{{siyuaninnerlink}}`：插入参考文献不能只考虑“入”，还要考虑“出”

非常赞的插件，超出我的预期了，尤其是可以将zotero中的笔记导入到思源笔记中，并且和当前插入点进行双向链接；

提一个如标题所示建议：

**原因：**
目前似乎是全部在思源笔记中非常好（带有思源笔记中的双链，可以预览），但是**考虑长远发展**，插入文献之后，还得考虑以后导出来（**通常是Word**），这个时候需要考虑是否可以方便地、**“近乎无损”地转换**（“无损”的意思是在Word中不用再次一个一个重新插入、整理参考文献，只需要一键更新、稍作调整即可），通用的做法是Pandoc+citation key方案（具体参考：[zotero 联合 markdown 软件 - 以思源笔记为例 暨 Pandoc 转换 markdown 为 Word - 链滴](https://ld246.com/article/1643468500328  )，[使用 Zotero 在 Markdown 中优雅地处理参考文献 - 少数派](https://sspai.com/post/60825  )），可能后续还需要社区贡献一个导出的插件（之前在思源社区提过，思源笔记导出的时候带Pandoc参数，但是搞了几个版本之后，D大放弃了，[关于导出 Word 的机制 - 链滴](https://ld246.com/article/1638283280873  )）。

**我的建议：**
插入到思源笔记中的“引用模板”引入变量`{{siyuaninnerlink}}`（就是类似`20230707113229-uraqhiq`这种，inner是区别于类似`siyuan://blocks/20230707105055-bm7xhwh`这样的outer链接，inner和outer是我自己定义的），这样的话，就可以插入`[@zhang2020] ((20230707113229-uraqhiq "*"))`这样的引用，这种引用兼顾思源笔记内部链接，又可以兼容Pandoc+citation key，对于“*”可以考虑使用其他字符，以便于在Word中可以批量替换掉。

##### 导出文献到Word

1. 目前（siyuan-plugin-citation v0.0.3）的导出方案（方案1）：

    1. 链接转为平文本：思源笔记中，一个个手动地把插入文献的双链转为文本，即把多个`((20230707105555-zmmh79y '[@zhang2020]'))`，转为`[@zhang2020]`，
    2. 思源笔记转到obsidian中：思源导出为markdown，或者直接思源笔记中Ctrl+C、obsidian中Ctrl+V，
    3. obsidian转为Word：再在obsidian中利用插件（[OliverBalfour/obsidian-pandoc: Pandoc document export plugin for Obsidian (https://obsidian.md)](https://github.com/OliverBalfour/obsidian-pandoc  )）转为带参考文献的Word；
2. 如果引入变量`{{siyuaninnerlink}}`，那么就可以在思源笔记中插入类似`[@zhang2020] ((20230707113229-uraqhiq "*"))`这样的引用，就不用方案1中的步骤1了，减少了很多工作量，对于“*”字符可以在Word中批量替换；
3. 后续社区如果有类似 [OliverBalfour/obsidian-pandoc: Pandoc document export plugin for Obsidian (https://obsidian.md)](https://github.com/OliverBalfour/obsidian-pandoc  ) 这样的思源笔记插件，导出流程就更方便了，就不用往obsidian转换了，目前对这个插件的思路是“思源笔记导出为临时markdown → 临时markdown按照Word模板、Pandoc参数转换为带文献引用的Word”，希望有大佬出手。

**Comment by Geo123abc** [comment]
说白了，就是让用户决定引用文献时，插入的文本内容

目前（v0.0.3）是用户可以决定在思源笔记中显示的内容是什么，但是不能决定内容对应的链接是什么

引入变量`{{siyuaninnerlink}}`之后，“引用模板”设置为

```x
“引用模板”设置为：
[@{{citekey}}](({{siyuaninnerlink}} "*"))

实例化之后就是：
[@zhang2020] ((20230707113229-uraqhiq "*"))
```
思源笔记中显示的效果（思源笔记主题选择naive）：

![](https://s3.bmp.ovh/imgs/2023/07/07/caa9781c3a5693e3.png)

**Comment by WingDr** [comment]
事实上我确实准备做这件事情，虽然目前没有很好的想法，[obsidian-pandoc](https://github.com/OliverBalfour/obsidian-pandoc)是个好东西，感谢提供，或许可以借鉴一下。

如果要做导出功能的话我就直接内部把链接转译然后导出了，不太需要用户单独设计引用模板，插件获取这些还是相对容易的。

目前插入引用是(( 文档ID "引用模板"))的样子，一方面是更新文档内部链接的时候是用双括号判断位置，然后只处理双括号内部的信息，尽量不要干扰到文档链接之外的内容，另一方面是考虑到很多用户对于思源内部引用机制并不了解，如果连链接都自定义的话可能会导致直接更新出文本没有引用。

这个issue先开着，啥时候我把导出这件事整好了啥时候关，开着能给我个提醒，感谢提供相关信息

**Comment by Geo123abc** [comment]
我目前想着插入的时候，可以按照 `[@{{citekey}}]((文档ID "引用模板"))`这种方式，相当于在现在（v0.0.3）插入的基础之上，可以再在前面加入`[@{{citekey}}]`，这个实例化之后就是`[@zhang2020]`这样子（是平文本，这个双括号不是markdown中的标记，是后续使用Pandoc转为Word时需要的一个标识符）。

这个存在的目的是方便后续Pandoc转换为Word的时候，直接把`[@zhang2020]`转变为一个引用（obsidian那边插入文献引用也是插入`[@{{citekey}}]`）（转换过程参看 [[在 Markdown 中引用文献](https://sspai.com/post/64842#:~:text=%E6%95%B0%E6%8D%AE%E7%9A%84%E4%BC%98%E5%8A%BF%E3%80%82-,%E5%9C%A8%20Markdown%20%E4%B8%AD%E5%BC%95%E7%94%A8%E6%96%87%E7%8C%AE,-%E5%8E%9F%E7%94%9F%20Markdown%20%E4%B8%8D)](https://sspai.com/post/64842#:~:text=%E6%95%B0%E6%8D%AE%E7%9A%84%E4%BC%98%E5%8A%BF%E3%80%82-,%E5%9C%A8%20Markdown%20%E4%B8%AD%E5%BC%95%E7%94%A8%E6%96%87%E7%8C%AE,-%E5%8E%9F%E7%94%9F%20Markdown%20%E4%B8%8D)，**强烈建议看一下这个内容**），转换过后的Word，和直接在Word中插入zotero中参考文献的格式是一样的。

**Comment by WingDr** [comment]
> 我目前想着插入的时候，可以按照 `[@{{citekey}}]((文档ID "引用模板"))`这种方式，相当于在现在（v0.0.3）插入的基础之上，可以再在前面加入`[@{{citekey}}]`，这个实例化之后就是`[@zhang2020]`这样子（是平文本，这个双括号不是markdown中的标记，是后续使用Pandoc转为Word时需要的一个标识符）。
> 
> 这个存在的目的是方便后续Pandoc转换为Word的时候，直接把`[@zhang2020]`转变为一个引用（obsidian那边插入文献引用也是插入`[@{{citekey}}]`）（ 转换过程参看 [在 Markdown 中引用文献](https://sspai.com/post/64842#:~:text=%E6%95%B0%E6%8D%AE%E7%9A%84%E4%BC%98%E5%8A%BF%E3%80%82-,%E5%9C%A8%20Markdown%20%E4%B8%AD%E5%BC%95%E7%94%A8%E6%96%87%E7%8C%AE,-%E5%8E%9F%E7%94%9F%20Markdown%20%E4%B8%8D) ，**强烈建议看一下这个内容**），转换过后的Word，和直接在Word中插入zotero中参考文献的格式是一样的。

嗯嗯，这篇文章我看过，我的意思是我准备直接在我这做导出.docx和.tex的功能，这样避免干预引用之外的内容（比如说用户把前面加的这段平文本删掉了一部分，那么在我更新整个文档的引用格式的时候，前面这部分文字到底要不要覆盖就是非常大的问题，我无法判断这是用户写的内容还是插入链接加上的）

**Comment by Geo123abc** [comment]
> 

这样统一考虑的话，确实是一个问题。

我之前的思路是导出为Word及其之后的事就和思源笔记无关了，思源笔记只是一个打草稿、践行卢曼卡片盒的工具，后续排版、调整引文格式之类的就交由Word进行；

从obsidian那边生态来看，导出参考文献也是 issue 这种思路；

从长远来看，比如哪天你不再维护这个项目了，可能会出问题，但是如果支持 这个issue提的这个建议的话，最起码后半截流程可以不依靠这个项目

至于大佬“更新整个文档的引用格式”这个功能我没有摸到门，没体会到；

至于“直接在我这做导出.docx”这个功能，是否支持后续在Word中追加、改动、删去之前在思源笔记中插入的zotero文献？（这个很重要）

最后，事情简单化思考，允许块ID那个链接不是包裹全部插入内容，即可以插入“[@zhang2020]”这样的平文本，这样也不影响你整个功能设计，只是具体到用户是选择后续你出的导出为Word功能，还是选择自己使用Pandoc、obsidian进行转换，那就用户自己决定，相当于给用户多了一个选择。

以上是我的观点。

**Comment by WingDr** [comment]
> 我之前的思路是导出为Word及其之后的事就和思源笔记无关了，思源笔记只是一个打草稿、践行卢曼卡片盒的工具，后续排版、调整引文格式之类的就交由Word进行；
> 
> 从obsidian那边生态来看，导出参考文献也是 issue 这种思路；

事实上我的思路过程是一样的，只不过是在插件内部先把思源的引用处理为[@citekey]的格式然后交给pandoc，到时候在做导出的时候我也会做一个“复制为带引用的markdown”这个操作，方便你进行你自己的工作流。换句话说，关于这个问题
> 至于“直接在我这做导出.docx”这个功能，是否支持后续在Word中追加、改动、删去之前在思源笔记中插入的zotero文献？（这个很重要）

在导出.docx之后，里面的内容就没有citation插件添加的内容了，有的只是pandoc对[@citekey]导出的内容，这部分是否能和zotero进行联动我还要仔细再看一遍[在 Markdown 中引用文献](https://sspai.com/post/64842#:~:text=%E6%95%B0%E6%8D%AE%E7%9A%84%E4%BC%98%E5%8A%BF%E3%80%82-,%E5%9C%A8%20Markdown%20%E4%B8%AD%E5%BC%95%E7%94%A8%E6%96%87%E7%8C%AE,-%E5%8E%9F%E7%94%9F%20Markdown%20%E4%B8%8D)


然后就是关于
> 最后，事情简单化思考，允许块ID那个链接不是包裹全部插入内容，即可以插入“[@zhang2020]”这样的平文本，这样也不影响你整个功能设计，只是具体到用户是选择后续你出的导出为Word功能，还是选择自己使用Pandoc、obsidian进行转换，那就用户自己决定，相当于给用户多了一个选择。

为什么我坚持不影响链接外的文本，我举个简单的例子。比如现在用户插入了一个引用"[@zhang2020] ((引用链接))"，当他在修改自己的文本的时候，不小心把前面的文本改成了'[@zhang'或者'@zhang'或者干脆就是'ang]'，那么我如果对前面的文本更新，就很容易吞掉用户自己写的内容，但是如果我直接插入的话，这个前面的内容就会越来越多，一不注意整个内容就变了，还不方便统一修改

**Comment by WingDr** [comment]
[v0.0.4](https://github.com/WingDr/siyuan-plugin-citation/releases/tag/v0.0.4)版本中已添加相关内容
