### ISSUE TITLE
功能建议：文献库不局限于指定目录下的所有子笔记

### ISSUE THREAD

**Issue by HowcanoeWang** [WingDr/siyuan-plugin-citation#32]
当前插件需要选定一个笔记作为文献库，然后再里面新建和zotero联动的模板笔记，但文献多了之后，管理起来不是很方便。

个人的使用习惯是，为不同的研究课题(项目)新建项目笔记，然后相关的文献作为子笔记(用bibtex的citationkey为标题和别名)，目前已经积累了200+的笔记，迁移到目前的插件比较困难。

希望插件可以提供文献库模式切换，类似于思源笔记中的这种设置：

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/19968935/bd6f75b1-329e-4218-a85f-a4076f090189)

如果设定了文献库，则在下面插入新文献笔记，如果留空，则在当前文档下新建文件笔记。

为了方便文献库管理，可以使用自定义属性作为过滤，如使用自定义块，或书签，或命名符合一定规则，从而过滤出文献库，而不是某个指定笔记下的所有子笔记

如目前我的文献库过滤SQL使用如下规则：

```SQL
SELECT * FROM blocks WHERE ((name LIKE '%\_%\_%' escape '\') OR (alias LIKE '%\_%\_%' escape '\')) AND (type = 'd' OR type = 'i')
```

这样就把我所有的 `auther_title_year`这样的笔记都过滤出来了，可以用来参考

**Comment by HowcanoeWang** [comment]
另外，我的citation key一开始也是放在命名里的，后来改成了别名

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/19968935/a8ff9f2c-7316-4fc2-8464-3554d73925eb)

这么做的原因是，可以在引用的时候用标题来作为一个文献的快速总结

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/19968935/3e30814d-c47a-4425-8652-4d5c2e3972a6)

如果不需要，可以灵活的修改块引用链接中的名称，来达到只显示citation key的效果：

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/19968935/6bfa7ff8-e68f-4052-b4d7-11f4ac9aa8c2)

希望插件也可以提供类似的功能，如仅插入citation key，和插入完整标题，可以有更多的应用场景

**Comment by WingDr** [comment]
> 当前插件需要选定一个笔记作为文献库，然后再里面新建和zotero联动的模板笔记，但文献多了之后，管理起来不是很方便。
> 
> 个人的使用习惯是，为不同的研究课题(项目)新建项目笔记，然后相关的文献作为子笔记(用bibtex的citationkey为标题和别名)，目前已经积累了200+的笔记，迁移到目前的插件比较困难。
> 
> 希望插件可以提供文献库模式切换，类似于思源笔记中的这种设置：
> 
> ![image](https://user-images.githubusercontent.com/19968935/263589838-bd6f75b1-329e-4218-a85f-a4076f090189.png)
> 
> 如果设定了文献库，则在下面插入新文献笔记，如果留空，则在当前文档下新建文件笔记。
> 
> 为了方便文献库管理，可以使用自定义属性作为过滤，如使用自定义块，或书签，或命名符合一定规则，从而过滤出文献库，而不是某个指定笔记下的所有子笔记
> 
> 如目前我的文献库过滤SQL使用如下规则：
> 
> ```sql
> SELECT * FROM blocks WHERE ((name LIKE '%\_%\_%' escape '\') OR (alias LIKE '%\_%\_%' escape '\')) AND (type = 'd' OR type = 'i')
> ```
> 
> 这样就把我所有的 `auther_title_year`这样的笔记都过滤出来了，可以用来参考

怎么说呢，管理文献这个事情本来就不应该放在思源里面，毕竟你都用zotero了。只是因为思源强制显式储存所以才有文献库这么个东西，文献库里的内容更多的是作为zotero中条目的一个跳板，用来被块引和显示信息的。另一方面，文献库本身是对插件的一个限制，限制插件不多在其他的文档里多搞事情。

你说的这个我在想一个比较关键的问题：如果我在两个项目里同时引用了一个文献，那么另一个文献我是更新到第一次插入的那个地方还是直接新建？如果是前者的话对于第二次引用的地方和文献库没有本质区别，如果是后者的话我的整个插件就要重新写一遍，因为文献在zotero里面的key不再是它的唯一标识，这在插件里直接把最底层的原则给破坏了，但是这个做法带来的好处/扩展性，是否值得我真的重新写一遍？或者反正都开源了，考不考虑自己写一个？（狗头

**Comment by WingDr** [comment]
> 另外，我的citation key一开始也是放在命名里的，后来改成了别名
> 
> ![image](https://user-images.githubusercontent.com/19968935/263591516-a8ff9f2c-7316-4fc2-8464-3554d73925eb.png)
> 
> 这么做的原因是，可以在引用的时候用标题来作为一个文献的快速总结
> 
> ![image](https://user-images.githubusercontent.com/19968935/263591429-3e30814d-c47a-4425-8652-4d5c2e3972a6.png)
> 
> 如果不需要，可以灵活的修改块引用链接中的名称，来达到只显示citation key的效果：
> 
> ![image](https://user-images.githubusercontent.com/19968935/263591990-6bfa7ff8-e68f-4052-b4d7-11f4ac9aa8c2.png)
> 
> 希望插件也可以提供类似的功能，如仅插入citation key，和插入完整标题，可以有更多的应用场景

等D大支持行内样式的自定义属性之后，我会添加一个可以自定义的引用链接锚文本列表（就像obsidian里面的zotero intergration插件那样），到时候先选文献然后选引用链接模板（为什么现在不做就是为了确保刷新引用的时候能够刷新成正确的格式，所以需要存在自定义属性）

**Comment by HowcanoeWang** [comment]
> 如果我在两个项目里同时引用了一个文献，那么另一个文献我是更新到第一次插入的那个地方还是直接新建？

并不是要在思源笔记中管理文献，主要目的还是想兼容我目前存在的200+文献笔记。为了用这个插件，我需要把之前的文献笔记重新复制到插件新建的笔记中，然后把所有的块引用都手动更新，工作量有点巨大

当且仅当插入的文献在思源笔记中不存在时，才创建笔记，否则直接插入引用链接，其实就是和文献库没什么区别，只不过文献库是整个笔记本而不是某个文档

**Comment by HowcanoeWang** [comment]
> 到时候先选文献然后选引用链接模板

我一年前还是两年前跟D打好像提过自定义锚文本模板，然后D大三连 [狗头]

https://github.com/siyuan-note/siyuan/issues/4746

**Comment by WingDr** [comment]
> 主要目的还是想兼容我目前存在的200+散落在各处的文献笔记。为了用这个插件，我需要把之前的文献笔记重新复制到插件新建的笔记中，然后把所有的块引用都手动更新，工作量有点巨大

其实对于这种工作，可以直接用f佬的运行js插件，写点代码把散落的文献笔记移动到文献库路径下，然后把别名塞到custom-literature-key这个属性下面，再重启citation插件就可以无缝衔接使用了，也没必要在插件里塞另一套功能

**Comment by WingDr** [comment]
> > 到时候先选文献然后选引用链接模板
> 
> 我一年前还是两年前跟D打好像提过自定义锚文本模板，然后D大三连 [狗头]
> 
> [siyuan-note/siyuan#4746](https://github.com/siyuan-note/siyuan/issues/4746)

乐，最后这种东西还是得我们自己写，有自定义属性的话可以直接在块引里记录格式数据，就好多了

**Comment by HowcanoeWang** [comment]
> > 主要目的还是想兼容我目前存在的200+散落在各处的文献笔记。为了用这个插件，我需要把之前的文献笔记重新复制到插件新建的笔记中，然后把所有的块引用都手动更新，工作量有点巨大
> 
> 其实对于这种工作，可以直接用f佬的运行js插件，写点代码把散落的文献笔记移动到文献库路径下，然后把别名塞到custom-literature-key这个属性下面，再重启citation插件就可以无缝衔接使用了，也没必要在插件里塞另一套功能

其实就是一个插件开发者掉头发和用户掉头发的问题和拉扯👀
我看看有没有时间提个pr，设置笔记本为文献库然后搜索散落在各处的文献笔记

**Comment by WingDr** [comment]
> 其实就是一个插件开发者掉头发和用户掉头发的问题和拉扯👀 我看看有没有时间提个pr，设置笔记本为文献库然后搜索散落在各处的文献笔记

也不是掉不掉头发，要我写也行，主要是你之前用的时候是这个格式，别人用的话又是另一种格式（没准不放在别名就是放在命名里呢，或者放在另一个自定义属性里），这种个性化的东西最好还是自己写自己用吧。写出来代码放到论坛里大家都能改改自己用就好了，到时候我可以在README文档里置顶一下链接
