### ISSUE TITLE
引用不了

### ISSUE THREAD

**Issue by luoxxib** [WingDr/siyuan-plugin-citation#33]
思源笔记v2.10.2，引用时提示，zotero没有在运行

**Comment by WingDr** [comment]
插件更新之前可以用吗？选择的是better-bibtex还是debug-bridge模式？

**Comment by luoxxib** [comment]
更新之前没用过

**Comment by luoxxib** [comment]
这两个模式切换了几次就可以了




张
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WingDr/siyuan-plugin-citation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月3日(星期天) 中午1:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WingDr/siyuan-plugin-citation] 引用不了 (Issue #33)





 
插件更新之前可以用吗？选择的是better-bibtex还是debug-bridge模式？

**Comment by WingDr** [comment]
嘶，不清楚是啥问题，能用了就行，用的过程中有bug再来提
