### ISSUE TITLE
模板文件中获取时间不对

### ISSUE THREAD

**Issue by luoxxib** [WingDr/siyuan-plugin-citation#34]
zotero上文章信息中日期是这样：![image](https://github.com/WingDr/siyuan-plugin-citation/assets/9431773/25bc9a0b-5a3c-426e-a460-1d33f2b20f91)
但思源上论文信息中的年年份是这样：
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/9431773/531d0c2f-9a8d-4872-8374-9b766404c0b9)

**Comment by WingDr** [comment]
v0.2.9已修复
