### ISSUE TITLE
用户数据区域 | User Data 锚文本支持自定义吗？

### ISSUE THREAD

**Issue by mdzz2048** [WingDr/siyuan-plugin-citation#35]
不太习惯用 "User Data" 这个默认标题，设置里没有找到可以设置的地方。

如果目前没有的话，能否考虑支持自定义？

**Comment by WingDr** [comment]
目前是写死的，之后可能考虑自定义，主要是要做的东西太多了，这个优先级可能比较低

**Comment by WingDr** [comment]
新版本已推送
