### ISSUE TITLE
v0.3.0插件的一些bug 

### ISSUE THREAD

**Issue by fenshen000** [WingDr/siyuan-plugin-citation#37]
更新v0.3.0后，文献内容文档的用户数据区域及文档开头的引用出现了一系列问题：
1. 在引用新文献后，新生成的文献内容文档开头不再是引用，而是未完成转换的块引用格式，如下：
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/59b73988-3cb1-4aa5-982c-c9cb8f3509b3)
这样的话，每次更新文献内容都会出现如下警告：
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/eff1db4e-f6aa-4b3b-852b-1e144a66bf2b)
2. 用户数据区域的标题虽然可以自定义，但每次自定义后重新更新文献内容会恢复成undefined，过程如下：
![1](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/7687bfa2-cd32-4a01-8355-c4332dc7b2f1)
感觉是比较严重的bug了，大佬啥时候有空再修一修~

**Comment by WingDr** [comment]
我懂了，那个给我推pr的大佬没写默认，打开设置界面再关闭应该就好了，我明天改下

**Comment by WingDr** [comment]
已更新，看看问题是否还存在？

**Comment by fenshen000** [comment]
可以了，大佬~
另外发现原来用户数据标题是在设置里面修改的，不是直接在文档里面修改哈哈哈哈

**Comment by WingDr** [comment]
文档里也可以修改的，生成文档之后每次更新都不会更新这个标题，所以可以任意修改成自己喜欢的，只不过之前生成的标题没法自定义，有一个大佬给我推了代码自己加了这个功能

**Comment by fenshen000** [comment]
欧克，学到了
