### ISSUE TITLE
zotero笔记在思源笔记中不能正确渲染

### ISSUE THREAD

**Issue by Geo123abc** [WingDr/siyuan-plugin-citation#4]
zotero 中的笔记是markdown、HTML混排的（类似obsidian中那种渲染方式），这种笔记通过siyuan-plugin-citation从zotero导到思源笔记中，会出现渲染问题，可能**需要考虑转换一下格式**（如果强制使用HTML格式，即把单个zotero笔记中的内容渲染为一个HTML块，就会失去思源笔记中块的粒度，使得笔记的粒度“变粗”）。

在和zotero笔记兼容这一方面，obsidian相对要好很多，obsidian可以正确渲染zotero导过来的笔记（包括高亮颜色、笔记粒度等，可能两者的一些引擎相似，兼容markdown和HTML两者），这可能是和之前思源笔记把HTML渲染这一块砍了有关，不知道 siyuan-plugin-citation 插件能不能转换。

我只是提自己的感受哈，大佬勿烦。

**Comment by WingDr** [comment]
因为我这边日常使用里基本只包含pdf的批注，还以为整个都是HTML的格式orz

请问在zotero里通过什么方法做笔记会出现markdown和html混排的情况呢？或者说能不能提供包含一个比较复杂的note的bib文件？（在不涉及你的隐私的前提下）

我知道pdf批注的笔记是用<p>标签来分栏的，但是我不确定是不是所有种类的笔记都是这么分的（尤其是表格之类的到底是给我html渲染还是markdown）。如果没问题的话理论上通过处理是可以做到在思源里也达到类似的粒度的

**Comment by WingDr** [comment]
[v0.0.4](https://github.com/WingDr/siyuan-plugin-citation/releases/tag/v0.0.4)版本中已修复

**Comment by wangfh5** [comment]
我这里还是不能正确渲染zotero笔记，可能是我使用了zotero的一些语法，如多级标题，字体颜色等等，
<img width="840" alt="image" src="https://github.com/WingDr/siyuan-plugin-citation/assets/51868839/be6886f3-617a-4105-ab91-8728c2e30907">
<img width="857" alt="image" src="https://github.com/WingDr/siyuan-plugin-citation/assets/51868839/771e5b9e-9435-46e0-b3de-a692e01742a5">

**Comment by WingDr** [comment]
> 我这里还是不能正确渲染zotero笔记，可能是我使用了zotero的一些语法，如多级标题，字体颜色等等， <img alt="image" width="840" src="https://user-images.githubusercontent.com/51868839/258093439-be6886f3-617a-4105-ab91-8728c2e30907.png"> <img alt="image" width="857" src="https://user-images.githubusercontent.com/51868839/258093499-771e5b9e-9435-46e0-b3de-a692e01742a5.png">

这个参考 #15 ，需要思源2.9.8提供的新API，下个版本就会更新，之前我以为解决了但是其实没解决orz
