### ISSUE TITLE
文献内容同模板预期不符

### ISSUE THREAD

**Issue by Nyeilim** [WingDr/siyuan-plugin-citation#40]
我的文献内容模板
```

---

**Title**:	{{title}}

**Author**:	{{authorString}}

**Year**:	{{year}}

---

# Abstract

{{abstract}}

# Select on Zotero

[zotero]({{zoteroSelectURI}})

# Files

{{files}}

# Annotations

{{annotations}}

```

实际呈现有问题的地方如下:
问题一:
![图一](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/cc07b753-8df9-4ae9-a9df-1482b5799e07)
问题二:
![图二](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/96a92468-3101-45d6-a47b-9a0f44ede407)

其实有点吹毛求疵了, 插件很棒!!

**Comment by WingDr** [comment]
annotation是插入的内容里就带个分割线，因为有可能存在一个条目下有多个文件被添加批注的情况，这种会用分割线分割，这点我记下，之后有可能把最前面的分割线去掉，这样只有一个被批注文件的时候就没有分割线了

第二个问题我复现不出来诶，理论上这里就是open后面少了个缩进，但是我这多文件的都是正常的

<img width="405" alt="image" src="https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/1409f94c-afeb-4fae-a140-f5f32ce01325">

方便的话能不能把这个条目打包发我下？

**Comment by Nyeilim** [comment]
> annotation是插入的内容里就带个分割线，因为有可能存在一个条目下有多个文件被添加批注的情况，这种会用分割线分割，这点我记下，之后有可能把最前面的分割线去掉，这样只有一个被批注文件的时候就没有分割线了
> 
> 第二个问题我复现不出来诶，理论上这里就是open后面少了个缩进，但是我这多文件的都是正常的
> 
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/63407442/273396153-1409f94c-afeb-4fae-a140-f5f32ce01325.png">
> 方便的话能不能把这个条目打包发我下？

[错误条目.zip](https://github.com/WingDr/siyuan-plugin-citation/files/12839540/default.zip)

**Comment by WingDr** [comment]
emmmm我这里是完全正常的……

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/7ed71be0-9ba2-491c-a620-e8db5130aa54)

这里的缩进都是写死的，我确定没有漏掉什么，看看多试几次或者重启一下思源能不能行？实在不行就把模板里面的`{{files}}`替换成下面这个：
```js
{{fileList.map(file => {if (file.type === "pdf") return `[[Open]](${file.zoteroOpenURI})\t|\t[${file.fileName}](${file.path})`; else return `[[Locate]](${file.zoteroSelectURI})\t|\t[${file.fileName}](${file.path})`;}).join("\n")}}
```
我感觉至少80%的可能性是思源的问题orz

**Comment by Nyeilim** [comment]
定位到问题了, 我把字符串粘贴下来转义发现确实有个 \t 的符号;
但是我安装了一个 savor 的思源主题, 不知道为啥显示异常;
用思源的默认主题就显示正常了
<img width='600px' src='https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/7fb30057-eece-47db-8b5f-7ceb4dd1a918'/>
<img width='600px' src='https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/82f1a5dd-83f5-465c-9f82-e4aeff752b1a'/>

话说你这是啥主题...

**Comment by WingDr** [comment]
> 定位到问题了, 我把字符串粘贴下来转义发现确实有个 \t 的符号; 但是我安装了一个 savor 的思源主题, 不知道为啥显示异常; 用思源的默认主题就显示正常了 <img alt="" width="600px" src="https://user-images.githubusercontent.com/33322256/273425375-7fb30057-eece-47db-8b5f-7ceb4dd1a918.png"> <img alt="" width="600px" src="https://user-images.githubusercontent.com/33322256/273425477-82f1a5dd-83f5-465c-9f82-e4aeff752b1a.png">
> 
> 话说你这是啥主题...

okk，你看更新下主题以及更新下思源版本行不行，我这个用的就是Savor，Salt配色的，加上背景图插件和背景方格插件，然后自己改了下编辑器字体

**Comment by Nyeilim** [comment]
难绷啊.. 我两更新了, 重启了电脑还是不行
真是逼死强迫症😂....

**Comment by WingDr** [comment]
> 难绷啊.. 我两更新了, 重启了电脑还是不行 真是逼死强迫症😂....

好家伙……如果会HTML的话可以开控制台看下啥问题，或者多切换一下Savor的设置之类的，我去帮你问问Savor的开发者

**Comment by Nyeilim** [comment]
> > 难绷啊.. 我两更新了, 重启了电脑还是不行 真是逼死强迫症😂....
> 
> 好家伙……如果会HTML的话可以开控制台看下啥问题，或者多切换一下Savor的设置之类的，我去帮你问问Savor的开发者

我好像理解为什么了?
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/f11ad8cb-13ea-47f7-958b-5871602984e0)
我已经不知道算不算 BUG 了, 你看嘛
这张图是我尝试修改下 HTML 后的结果
[Open] 后面过去一点点就是刚好制表符对齐的地方, 然后所以这个 Open 后面的制表符就非常非常窄(图中高亮那块)
如果你把 Open 稍微加长点或者缩短点, 制表符的显示又差不多是正常的了

(但是其实也解释不通为啥你的思源不会有这样的情况....)
所以如果要修改的话, 我感觉就是修改模板, 把 Open, Locate 统一成同样长度的文字 'Open'
类似下面这样
```js
{{fileList.map(file => {if (file.type === "pdf") return `[[Open]](${file.zoteroOpenURI})\t|\t[${file.fileName}](${file.path})`; else return `[[Open]](${file.zoteroSelectURI})\t|\t[${file.fileName}](${file.path})`;}).join("\n")}}
```
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/d7b23255-8739-43fd-8f72-548c35ccf5f9)

---
好了, 强迫症可以安心看论文了...

**Comment by Nyeilim** [comment]
> > > 难绷啊.. 我两更新了, 重启了电脑还是不行 真是逼死强迫症😂....
> > 
> > 
> > 好家伙……如果会HTML的话可以开控制台看下啥问题，或者多切换一下Savor的设置之类的，我去帮你问问Savor的开发者
> 
> 我好像理解为什么了? ![image](https://user-images.githubusercontent.com/33322256/273432914-f11ad8cb-13ea-47f7-958b-5871602984e0.png) 我已经不知道算不算 BUG 了, 你看嘛 这张图是我尝试修改下 HTML 后的结果 [Open] 后面过去一点点就是刚好制表符对齐的地方, 然后所以这个 Open 后面的制表符就非常非常窄(图中高亮那块) 如果你把 Open 稍微加长点或者缩短点, 制表符的显示又差不多是正常的了 然后也能解释的通为啥思源默认主题就可以, 因为前面少了个图标, 使得它们两能在同一个制表符上对齐....
> 
> (但是其实也解释不通为啥你的思源不会有这样的情况....你屏幕大? 字体小?) 所以如果要修改的话, 我感觉就是修改模板, 把 Open, Locate 统一成同样长度的文字 'Open' 类似下面这样
> 
> ```js
> {{fileList.map(file => {if (file.type === "pdf") return `[[Open]](${file.zoteroOpenURI})\t|\t[${file.fileName}](${file.path})`; else return `[[Open]](${file.zoteroSelectURI})\t|\t[${file.fileName}](${file.path})`;}).join("\n")}}
> ```
> 
> ![image](https://user-images.githubusercontent.com/33322256/273433358-d7b23255-8739-43fd-8f72-548c35ccf5f9.png)
> 
> 好了, 强迫症可以安心看论文了...

好吧最近发现使用自定义的模板又有个错误, 在思源的 PDF 链接里面没有路径的分隔符
好气啊... 要不我也学学 JS 看看怎么改吧
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/782eec94-4201-4995-9096-1a0d9a254603)

**Comment by WingDr** [comment]
> 好吧最近发现使用自定义的模板又有个错误, 在思源的 PDF 链接里面没有路径的分隔符
> 好气啊... 要不我也学学 JS 看看怎么改吧

啊？不应该啊，我没有动这个分隔符。最简单的办法，我把所有信息都放在模板生成文档的自定义属性"entry-data"里面了，你可以把它复制出来然后查找一下“path”，找到类似这样的东西

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/4b8f554f-3d5c-4874-946f-ba12f457e3a0)

attachments下的path，这个就是传给citation插件的文件路径，康康是啥情况。程序里面应该只处理了 #28 中提到的括号转义的问题，没有动中间的分隔符。

另外欢迎来学js（实际上是ts）然后自己加功能，我最近贼忙（被安排了个新方向）所以想的好多东西都还没动手写。我自认为目前citation的程序架构安排算是比较合理和直观的，想要开始学插件写法的话完全可以参考

**Comment by Nyeilim** [comment]
> > 好吧最近发现使用自定义的模板又有个错误, 在思源的 PDF 链接里面没有路径的分隔符
> > 好气啊... 要不我也学学 JS 看看怎么改吧
> 
> 啊？不应该啊，我没有动这个分隔符。最简单的办法，我把所有信息都放在模板生成文档的自定义属性"entry-data"里面了，你可以把它复制出来然后查找一下“path”，找到类似这样的东西
> 
> ![image](https://user-images.githubusercontent.com/63407442/274818120-4b8f554f-3d5c-4874-946f-ba12f457e3a0.png)
> 
> attachments下的path，这个就是传给citation插件的文件路径，康康是啥情况。程序里面应该只处理了 #28 中提到的括号转义的问题，没有动中间的分隔符。
> 
> 另外欢迎来学js（实际上是ts）然后自己加功能，我最近贼忙（被安排了个新方向）所以想的好多东西都还没动手写。我自认为目前citation的程序架构安排算是比较合理和直观的，想要开始学插件写法的话完全可以参考

我检查了下, 确实是有问题, 附件的路径一共出现在三个字段里面 `files` `attachments` `fileList`
前两个字段里的都没有问题, 第三个字段就有问题
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/c90fc9d9-b99e-4727-870b-95a1a5efd30c)

**Comment by WingDr** [comment]
> 我检查了下, 确实是有问题, 附件的路径一共出现在三个字段里面 `files` `attachments` `fileList` 前两个字段里的都没有问题, 第三个字段就有问题 ![image](https://user-images.githubusercontent.com/33322256/274849911-c90fc9d9-b99e-4727-870b-95a1a5efd30c.png)

我知道了，是我这的问题，fileList里面的处理忘记删了（有一个去掉转义字符的操作，之前光改file了来着），马上推个版本改一下
