### ISSUE TITLE
第二次插入Zotero反向链接时, Zotero链接附件标题显示为空

### ISSUE THREAD

**Issue by Nyeilim** [WingDr/siyuan-plugin-citation#42]
环境: win11 zotero7 siyuan2.10.6

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/e7eaee00-2364-4332-b097-ed8710f6ecc5)
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/a2da250a-316b-4f87-a714-5c82e2b72fa8)

顺便说下第三次第四次等等也是哦

**Comment by Nyeilim** [comment]
要为条目建立反向链接可以这样, 给后来人当个备用方案
1. 修改数据文件夹\locate\engine.json
```json
{
  "_name": "思源笔记",
  "_alias": "SiyuanNote",
  "_description": "Zotero Link Siyuan",
  "_icon": "https://b3log.org/images/brand/siyuan-128.png",
  "_hidden":false,
  "_urlTemplate": "siyuan://blocks/{z:archive}",
  "_urlParams": [],
  "_urlNamespaces": {
	  "z": "http://www.zotero.org/namespaces/openSearch#",
	  "": "http://a9.com/-/spec/opensearch/1.1/"
  },
  "_iconSourceURI": "https://b3log.org/images/brand/siyuan-128.png"
},
```
2. 在档案号添加
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/46b8b1d6-bc20-4111-9758-e3b3e022d54e)
3. 触发思源的链接
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/c1de8d84-0040-4f94-aa44-a1f239cbe382)

**Comment by WingDr** [comment]
> 环境: win11 zotero7 siyuan2.10.6
> 
> ![image](https://user-images.githubusercontent.com/33322256/271783083-e7eaee00-2364-4332-b097-ed8710f6ecc5.png) ![image](https://user-images.githubusercontent.com/33322256/271783095-a2da250a-316b-4f87-a714-5c82e2b72fa8.png)
> 
> 顺便说下第三次第四次等等也是哦

ok，等我有空了测试下，之前写的时候没问题，大概后面修改的时候又有bug了

**Comment by WingDr** [comment]
> 要为条目建立反向链接可以这样, 给后来人当个备用方案
> 
> 1. 修改数据文件夹\locate\engine.json
> 
> ```json
> {
>   "_name": "思源笔记",
>   "_alias": "SiyuanNote",
>   "_description": "Zotero Link Siyuan",
>   "_icon": "https://b3log.org/images/brand/siyuan-128.png",
>   "_hidden":false,
>   "_urlTemplate": "siyuan://blocks/{z:archive}",
>   "_urlParams": [],
>   "_urlNamespaces": {
> 	  "z": "http://www.zotero.org/namespaces/openSearch#",
> 	  "": "http://a9.com/-/spec/opensearch/1.1/"
>   },
>   "_iconSourceURI": "https://b3log.org/images/brand/siyuan-128.png"
> },
> ```
> 
> 2. 在档案号添加
>    ![image](https://user-images.githubusercontent.com/33322256/271783381-46b8b1d6-bc20-4111-9758-e3b3e022d54e.png)
> 3. 触发思源的链接
>    ![image](https://user-images.githubusercontent.com/33322256/271783537-c1de8d84-0040-4f94-aa44-a1f239cbe382.png)

这样最大的问题是如果“档案”这个词条本身被占用的话也无解，其实本质上是zotero不支持外部添加可储存的自定义属性（除非像bbt一样自己建库），或许哪天这个真的很有用了再整个配套的zotero插件也说不准

**Comment by WingDr** [comment]
> 环境: win11 zotero7 siyuan2.10.6
> 
> ![image](https://private-user-images.githubusercontent.com/33322256/271783083-e7eaee00-2364-4332-b097-ed8710f6ecc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTM2MTAsIm5iZiI6MTcwNDk1MzMxMCwicGF0aCI6Ii8zMzMyMjI1Ni8yNzE3ODMwODMtZTdlYWVlMDAtMjM2NC00MzMyLWIwOTctZWQ4NzEwZjZlY2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA2MDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZDM5N2RiMGE3ZjI2ZTQ5NGMyMjcyNzc0ZjFmOWEwMTY5MDg3MjhkNDMzOTc5ODNiZWUzMzZjOGMwZDY4NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IL0y1mkETZugTfjwMYzmCYxZGbbFKlqonqIchP0zbDY) ![image](https://private-user-images.githubusercontent.com/33322256/271783095-a2da250a-316b-4f87-a714-5c82e2b72fa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTM2MTAsIm5iZiI6MTcwNDk1MzMxMCwicGF0aCI6Ii8zMzMyMjI1Ni8yNzE3ODMwOTUtYTJkYTI1MGEtMzE2Yi00Zjg3LWE3MTQtNWM4MmUyYjcyZmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA2MDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZjZjNDk2OWNlODViNTM3ODRiMGMxY2JmNDgyOTA5OThhOWYwNTNlZDA0NzIwYTI4ODNkNzU3Nzg5MTE1ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.opB6l489p0cotwnrNRHVQRhNxpgi1GF_dfBJtMXvi0M)
> 
> 顺便说下第三次第四次等等也是哦

我知道为什么你那个会显示空了，仔细看了下那个`siyuanLink`的L你写的是小写，查找不到变量就空了，我这试了半天都没法复现

**Comment by WingDr** [comment]
> 要为条目建立反向链接可以这样, 给后来人当个备用方案
> 
> 1. 修改数据文件夹\locate\engine.json
> 
> ```json
> {
>   "_name": "思源笔记",
>   "_alias": "SiyuanNote",
>   "_description": "Zotero Link Siyuan",
>   "_icon": "https://b3log.org/images/brand/siyuan-128.png",
>   "_hidden":false,
>   "_urlTemplate": "siyuan://blocks/{z:}",
>   "_urlParams": [],
>   "_urlNamespaces": {
> 	  "z": "http://www.zotero.org/namespaces/openSearch#",
> 	  "": "http://a9.com/-/spec/opensearch/1.1/"
>   },
>   "_iconSourceURI": "https://b3log.org/images/brand/siyuan-128.png"
> },
> ```
> 
> 2. 在档案号添加
> 
> <img alt="" width="600px" src="https://private-user-images.githubusercontent.com/33322256/271783381-46b8b1d6-bc20-4111-9758-e3b3e022d54e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTM2MTAsIm5iZiI6MTcwNDk1MzMxMCwicGF0aCI6Ii8zMzMyMjI1Ni8yNzE3ODMzODEtNDZiOGIxZDYtYmMyMC00MTExLTk3NTgtZTNiM2UwMjJkNTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA2MDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwOWU3YjUxZmFiNWI1YjQ5ODc3NjNiZTJlODcyZjU1ZGZmOTJjYjYxYmQwNTNhNzAxY2JmMGRlZGVkZDU2ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TR93DcLiynnOutXO1qtWOoRbO0UvLWmXyxeVXEVOKsg">
> 3. 触发思源的链接
> 
> <img alt="" height="400px" src="https://private-user-images.githubusercontent.com/33322256/271783537-c1de8d84-0040-4f94-aa44-a1f239cbe382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTM2MTAsIm5iZiI6MTcwNDk1MzMxMCwicGF0aCI6Ii8zMzMyMjI1Ni8yNzE3ODM1MzctYzFkZThkODQtMDA0MC00Zjk0LWFhNDQtYTFmMjM5Y2JlMzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA2MDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YTI4MTczYjM2ZmMzYWQ2OWFkYjlmZjMwM2UwMTg5MTlmYTI0OWM4NzliNGQyZDQ2YzljY2UxN2U2ZGI0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2CDF6acg3zWfq3S5QXCeFzCgPudZEOHDlPrmxno2yF0">

这个我现在有办法做了，开个新issue，不需要改变zotero那边的词条位置
