### ISSUE TITLE
使用citationKey作索引会找不到key

### ISSUE THREAD

**Issue by Junbin6** [WingDr/siyuan-plugin-citation#43]
如题，今天写东西的时候发现通过插件的搜索框插入条目时，有PDF文件的条目可以在思源中引用，没有PDF就不能引用。使用引用选中条目功能则没有影响
思源版本2.10.11
插件版本0.3.2

**Comment by WingDr** [comment]
那个无法插入的条目的信息能看下吗？如果不涉及隐私的最好能导出一下我去测试。我这边也有无附件的条目，但是都能成功引用，应该不是没有pdf的问题。

此外麻烦你通过下面图里的方式打开一下控制台，然后再引用一下你说的无法引用的条目，看看有没有红色的报错，有的话麻烦给我截一下图，感谢。

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/d26edc43-8ac0-4b7b-ad89-8c077a3e1b24)

**Comment by Junbin6** [comment]
plugin:siyuan-plugin-citation:75 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at ZoteroDBModal.eval (plugin:siyuan-plugin-citation:75:1038)
    at Generator.next (<anonymous>)
    at a (plugin:siyuan-plugin-citation:49:20934)

**Comment by Junbin6** [comment]
是我的模版有问题吗？

**Comment by WingDr** [comment]
> 是我的模版有问题吗？

不，看起来不是，模板有问题的话应该是另一个东西报错，这里报错的是读取数据的地方

**Comment by WingDr** [comment]
> 不会加图片，我把代码复制过来了。每次插入失败都是这个代码 plugin:siyuan-plugin-citation:75 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length') at ZoteroDBModal.eval (plugin:siyuan-plugin-citation:75:1038) at Generator.next () at a (plugin:siyuan-plugin-citation:49:20934)

能点到ZoteroDBModal那一行报错对应的代码吗？看看是哪里的问题。最好还是能看下条目到底是啥样的（图片或者文件直接复制到github的输入框里就能上传了

**Comment by Junbin6** [comment]
[127.0.0.1-1697716341488.log](https://github.com/WingDr/siyuan-plugin-citation/files/13042177/127.0.0.1-1697716341488.log)
<img width="1164" alt="截屏2023-10-19 19 53 42" src="https://github.com/WingDr/siyuan-plugin-citation/assets/118649962/0180bfa0-ccfc-4b5f-bf9d-3fcec9c70066">

**Comment by Junbin6** [comment]
<img width="1094" alt="截屏2023-10-19 19 55 22" src="https://github.com/WingDr/siyuan-plugin-citation/assets/118649962/0817ce49-6275-441a-9a4f-d6a69ee65405">

**Comment by WingDr** [comment]
> 应该是这个吧？<img alt="截屏2023-10-19 19 55 22" width="1094" src="https://user-images.githubusercontent.com/118649962/276604676-0817ce49-6275-441a-9a4f-d6a69ee65405.png">

好家伙现在居然还有这里的问题emmm那有点麻烦了

先确认一下你的设置？是用debug-bridge然后用的citationKey作为索引（就是下面的开关是关闭的）？

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/913c5fa3-babd-4928-b236-b207d23ceba0)

**Comment by Junbin6** [comment]
<img width="646" alt="截屏2023-10-19 20 09 13" src="https://github.com/WingDr/siyuan-plugin-citation/assets/118649962/5df60e71-a22f-4d43-8f55-9b42baaede26">


> > 应该是这个吧？<img alt="截屏2023-10-19 19 55 22" width="1094" src="https://user-images.githubusercontent.com/118649962/276604676-0817ce49-6275-441a-9a4f-d6a69ee65405.png">
> 
> 好家伙现在居然还有这里的问题emmm那有点麻烦了
> 
> 先确认一下你的设置？是用debug-bridge然后用的citationKey作为索引（就是下面的开关是关闭的）？
> 
> ![image](https://user-images.githubusercontent.com/63407442/276607228-913c5fa3-babd-4928-b236-b207d23ceba0.png)

用的debug-bridge，下面开关没有开

**Comment by WingDr** [comment]
> 用的debug-bridge，下面开关没有开。 如果是两个插件并用引起的，是不是可以只用debug-bridge。 相对要兼容两个插件，只维护一个插件是不是方便一点？ <img alt="截屏2023-10-19 20 09 13" width="646" src="https://user-images.githubusercontent.com/118649962/276608020-5df60e71-a22f-4d43-8f55-9b42baaede26.png">

okk，然后得确认下citationKey的格式，看下zetero里bbt插件的设置是啥样的？
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/1ce56fd2-0e9d-4abc-bb85-a2bd6d4db7e5)

如果能看到插入不了引用的那个条目的citationKey就更好了

这个地方说白了是因为当时为了把索引改成itemKey，但是又要兼容之前使用citationKey的用户所以要对这些进行处理，但是citationKey的设置可以是各种各样的，这里也不可能说非常完美地处理好。所以说如果用debug-bridge的话最好还是用itemKey作为索引，毕竟zotero内部的这个索引本身格式是固定的，不会出现处理上的问题

**Comment by Junbin6** [comment]
<img width="838" alt="截屏2023-10-19 20 23 19" src="https://github.com/WingDr/siyuan-plugin-citation/assets/118649962/4af3fea2-3380-4ff6-8dee-fca5dac10351">
条目citekey： Fu.etal_JournalofIntegrativeAgriculture_2023。
可能有的长……。
我后面就切换成itemKey。反正现在标题是自定义的。之前没发现影响使用，就懒得换。

**Comment by WingDr** [comment]
> <img alt="截屏2023-10-19 20 23 19" width="838" src="https://user-images.githubusercontent.com/118649962/276611531-4af3fea2-3380-4ff6-8dee-fca5dac10351.png"> 条目citekey： Fu.etal_JournalofIntegrativeAgriculture_2023。 可能有的长……。 我后面就切换成itemKey。反正现在标题是自定义的。之前没发现影响使用，就懒得换。

好，我去试试，解决了之后会推送一个新版本，不过建议还是换成itemKey，谁知道后面还会不会有别的问题orz

**Comment by WingDr** [comment]
虽然更新了新版本，但是这个bug我还是没有特别多的头绪（你给的citationKey解析起来是没问题的，那应该不是报错那个函数的问题，可能是更里面的问题），总之还是先切换成itemKey吧
