### ISSUE TITLE
macOS「插入文献笔记」无反应

### ISSUE THREAD

**Issue by fengqiii** [WingDr/siyuan-plugin-citation#45]
请问「插入文献笔记」是会引用思源中的那个文档吗？
如果是上面的引用文献，就会创建多个文档了。
因为目前macOS上「插入文献笔记」没有反应，所以不太确定。
因为想在思源里重复引用那个文献，然后发现一长串英文数字的命名实在不行。。
思源：v2.10.12
macOS：14.0 M1

**Comment by WingDr** [comment]
插入文献笔记是用来往思源里插入在zotero里记的笔记的，只有条目有笔记才会插入，会显示在zotero侧栏的这里

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/9235a5a0-1136-4b79-980c-e9718d948c0f)

重复引用的话只要再插入引用就可以了，如果已经创建了文档不会重复创建的，只会刷新内容。觉得插入的引用链接太长是可以改模板的，在插件的`设置->模板设置->引用模板`里，具体怎么写可以参考插件的说明

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/f164829b-a843-4643-8bd2-521c3f5e44cc)
