### ISSUE TITLE
{{annotations}} 错误

### ISSUE THREAD

**Issue by fengqiii** [WingDr/siyuan-plugin-citation#46]
<img width="742" alt="image" src="https://github.com/WingDr/siyuan-plugin-citation/assets/75001434/99fb5eac-6a17-4219-9505-01bb0dfb85d9">
本来还是好好的，我在修改模板的过程中一次刷新后就一直这样了，{之间有一个空格

**Comment by WingDr** [comment]
这个是刷新过程中的占位符，目前是有可能一直这样刷新不出来的，可以用面包屑菜单里的“刷新文献内容”刷新一下再看看，刷新之后多等一会儿，可能会反应比较慢，这个和电脑的性能有关的

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/39571b55-aa86-48f2-a13b-668efd8fd72a)
