### ISSUE TITLE
模板不会跟随思源而同步吗？

### ISSUE THREAD

**Issue by fengqiii** [WingDr/siyuan-plugin-citation#47]
正在Mac和PC上换着用，发现不行。

**Comment by WingDr** [comment]
诶，肯定会同步的啊，首先确定模板保存了（关闭设置界面会自动保存，再打卡可以确认），然后同步。另一边可以先把同步设置成完全手动，然后再从云端同步下来，这样的话应该能确保设置是同步过来的。

自动同步有可能有一定延迟，不要太着急打开插件的设置界面，因为关闭设置界面会自动保存，可能会导致同步冲突，可以用插入引用试一下模板是不是同步过来了
