### ISSUE TITLE
User Data可以是不只是纯文本吗

### ISSUE THREAD

**Issue by fengqiii** [WingDr/siyuan-plugin-citation#48]
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/75001434/92c96c20-7d67-400c-9a9e-06094728d2a3)
`20231027143412-vaz2pbj`是标题块的id，我在模板中把User Data改成了((20231027131816-1o0mx6n 'User Data'))也就是文档块的id，用来直接汇总的。
因为User Data的特殊性所以我也不是很懂，对Annotations这样做是完全没问题的。
现在的情况就是文献引用的第一行的这个出现了错误，如果引号内是纯文本是不是就可以了呢？我复制第一行为纯文本再粘贴就达成了我需要的效果。

**Comment by WingDr** [comment]
最前面的User Data引用本质上就是给快速跳转到最后自定义区域的一个链接（也会给插件提供自定义区域的识别），最好是纯文本，否则会破坏思源本身的引用格式（插件的输入不像用户输入一样会经过多层处理所以有时候会有问题）

User Data后面的区域在再次插入引用/刷新文献内容的时候是不会刷新的，包括User Data这个标题本身，具体的需求是从 #6 来的。至于为什么有最开头这个引用是考虑到有时候note和annotation会非常长，这样的话想要记一些笔记拖到底很麻烦，给一个引用可以直接跳转就会方便很多，也方便插件识别哪里能刷新哪里不能刷新
