### ISSUE TITLE
初次插入文献时，向zotero父条目中插入思源笔记回链（siyuan://）

### ISSUE THREAD

**Issue by Geo123abc** [WingDr/siyuan-plugin-citation#5]
1. 初次生成`/References/zhang2020`文件之后，往zotero中对应父条目下插入一个`siyuan://blocks/20230319100022-ztjt9lo`这样的思源笔记URL链接，链接的内容是`/References/zhang2020`标题的块链接；
2. 当再次插入文献、更新`/References/zhang2020`文件时，不添加、也不增加`siyuan://blocks/20230319100022-ztjt9lo`这样的思源笔记URL链接。
3. 如果用户手动删除了`/References/zhang2020`文件，会导致用户第一次插入这篇文献时生成的`siyuan://`回链失效，那就只能靠用户自己手动更新zotero中的父条目下的`siyuan://`链接；

这样也方便zotero和思源笔记联合；

我只是提自己的感受哈，大佬勿烦。

**Comment by Geo123abc** [comment]
> 这个东西的主要问题是需要zotero那边的插件或者说API配合，目前zotero的API全部都是网络请求的api，也就是说要求用户注册zotero账户并且申请api key，这个过程对于国内用户是很困难的，尤其是注册账户需要肉身在国外，翻墙都不行（我当初就是拜托在国外的朋友帮我注册的）。
> 
> 目前zotero integration的原理是通过better bibtex插件提供的API获得数据，但是这个插件本身也没有提供写入的方法。
> 
> 如果能够有什么方法直接通过zotero客户端写入的话，我也是很乐意尝试这件事情的。

我完全拒绝网络版的zotero，
zotero往外导出的参数倒是很多，但是往zotero数据库写入的好像很少
这个issue就看缘分吧

**Comment by WingDr** [comment]
> 我完全拒绝网络版的zotero， zotero往外导出的参数倒是很多，但是往zotero数据库写入的好像很少 这个issue就看缘分吧

对的，除非谁能写一个zotero的写入插件，但是还要考虑到extra词条本身会和很多很多东西冲突的情况，真的挺难的。到时候如果真有这种方法可以再开这个issue，我相信这个citation插件会一直更新的（毕竟我自己也一直在用）

**Comment by Geo123abc** [comment]
> > 我完全拒绝网络版的zotero， zotero往外导出的参数倒是很多，但是往zotero数据库写入的好像很少 这个issue就看缘分吧
> 
> 对的，除非谁能写一个zotero的写入插件，但是还要考虑到extra词条本身会和很多很多东西冲突的情况，真的挺难的。到时候如果真有这种方法可以再开这个issue，我相信这个citation插件会一直更新的（毕竟我自己也一直在用）

有个大佬，他搞的插件可以在zotero中新增栏，倒是可以请教一下，这个zotero插件不知道你用过没？
[MuiseDestiny/zotero-style: A Zotero plugin for creating a personal Zotero Style.](  https://github.com/MuiseDestiny/zotero-style  )    


另外我说的父条目下插入siyuan:// 链接可能和你理解的不一样，你理解的是插入到zotero条目信息中（类似“作者”、“摘要”、“期刊”、“日期”、“页码”这些字段）

我说的“向父条目下添加siyuan:// 链接”是如下图所示
