### ISSUE TITLE
User data 相关问题: 影响反链和提及的效果

### ISSUE THREAD

**Issue by HoollyFox** [WingDr/siyuan-plugin-citation#50]
user data 会作为一级标题，自动被反链提及索引，所以在反链提及面板会有好多 user data 提及，类似
<img width="315" alt="image" src="https://github.com/WingDr/siyuan-plugin-citation/assets/23378900/64b16b42-1b18-473a-8fa0-58bfc45b2342">

能否有方案解决此问题，或者把一级标题改成段落？

**Comment by WingDr** [comment]
这个提及是因为引用，和一级标题无关吧，而且当初设定一级标题的时候主要想的是可以直接预览下面的所有内容，不然想看自己写的东西还得往下翻好多，想不到有啥解决办法

**Comment by HoollyFox** [comment]
引用只会索引H123456 还有文档类，似乎正文不会索引。我也在 D 大那提意见给引用排除列表了。如果能有排除列表也可以解决这个问题。

**Comment by WingDr** [comment]
> 引用只会索引H123456 还有文档类，似乎正文不会索引。我也在 D 大那提意见给引用排除列表了。如果能有排除列表也可以解决这个问题。

哦哦，那主要问题还是在悬浮预览上，毕竟只有标题能带着下面的预览，最好还是看D大那边能不能弄个排除

**Comment by WingDr** [comment]
> 有一个临时办法，就是 user data 的自定义名称带着样式，比如斜体或者加粗，带着样式的文本不会被索引为提及，我用的是
> 
> ```
> ----*user data*----
> ```

好家伙居然还能这样，学会了，User Data的模板可以直接写markdown形式，用这种方法也不用每次再改了。这个issue我先关了，看D大那边能不能搞个筛选出来，目前暂时确实也只能这么干了

**Comment by WingDr** [comment]
根据 #61 ，后面会把这里的引用改成块超链接，就完全不会影响引用计数和反链提及了
