### ISSUE TITLE
对epub不生效吗

### ISSUE THREAD

**Issue by fengqiii** [WingDr/siyuan-plugin-citation#51]
今天刚安装zotero7还挺激动的。

**Comment by WingDr** [comment]
zotero 7 对equb目前只支持软件内部的编辑和高亮，我现在也想开发但是没给外部的接口，网页快照目前也是这样。估计最晚等7的正式版这些东西就都能完善了

**Comment by fengqiii** [comment]
> zotero 7 对equb目前只支持软件内部的编辑和高亮，我现在也想开发但是没给外部的接口，网页快照目前也是这样。估计最晚等7的正式版这些东西就都能完善了

愈发期待了
