### ISSUE TITLE
{{note}} 字段解析错误

### ISSUE THREAD

**Issue by HoollyFox** [WingDr/siyuan-plugin-citation#52]
经测试，当 note 以数字开头的时候，会出现该问题，且该 note 在zotero 条目 要排到第一个位置，情况如下： 
<img width="740" alt="image" src="https://github.com/WingDr/siyuan-plugin-citation/assets/23378900/56aca3ed-4874-4daf-884a-b3ffea5b24db">

在 zotero 的顺序显示为
<img width="275" alt="image" src="https://github.com/WingDr/siyuan-plugin-citation/assets/23378900/a82f4697-2cb9-4daf-9c97-c65c3cd2d50b">

> 该错误复现需要多次刷新文献内容才会出现，可能是 zotero 数据库的更新没那么及时导致。

**Comment by WingDr** [comment]
这个东西是插入HTML块（zotero传过来的笔记富文本）的占位符，再等下思源数据库索引结束就会刷新成笔记的具体内容。有时候刷太快确实也会出现内容更新不出来的问题，多等会儿然后再刷新一次就好了。

不过这里程序的逻辑可能确实还有点问题，我有空再理一下

**Comment by HoollyFox** [comment]
好的 🥹感谢
