### ISSUE TITLE
annotations 显示为六级标题

### ISSUE THREAD

**Issue by Nyeilim** [WingDr/siyuan-plugin-citation#53]
模板使用: {{annotations}}
插件版本: 0.3.3
显示效果:  
<img src="https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/3d70d8ca-1d94-4c36-a22b-df1f227dfabb" width='700px' />
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/84908296-fd5e-4640-a6a0-0df6f3419fce)
entry-data 相关信息: 
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/c7b16b5b-e23e-4693-858d-74c249343bef)

是 BUG 还是设计如此呢? 希望有帮助 😊

**Comment by WingDr** [comment]
设计上就是这样的，主要是希望可以从大纲快速跳转到对应文件的批注上

因为会有同一个条目多个文件中有批注的情况所以每个文件添加了标题

**Comment by Nyeilim** [comment]
> 设计上就是这样的，主要是希望可以从大纲快速跳转到对应文件的批注上
> 
> 因为会有同一个条目多个文件中有批注的情况所以每个文件添加了标题

啊我的意思是为啥是六级标题, 上面的不是 Annotations 一级标题嘛? 按道理这个应该是二级标题才对?

**Comment by WingDr** [comment]
> 啊我的意思是为啥是六级标题, 上面的不是 Annotations 一级标题嘛? 按道理这个应该是二级标题才对?

emmm因为插件是不知道变量外的情况的（除非在插件里整一套markdown解析，但是这很没有必要），所以设定为最小的标题能够保证满足绝大部分人的分栏需求，比如有的人喜欢给annotation放在二级或者三级标题，如果我这里设定成二级那么就没办法被包含在整个annotation里
