### ISSUE TITLE
在思源中打开zetero条目或文件报错

### ISSUE THREAD

**Issue by dtxdtx** [WingDr/siyuan-plugin-citation#54]
在思源笔记中打开zetero报错，如下图所示，点击zotero或open都会报错，其他功能都正常。
之前设置好了，一切正常，后来使用oneDrive同步zotero目录下的storage数据，按这篇文章操作的[[Zotero使用Onedrive实现云同步【附onedrive扩容教程】 - 知乎 (zhihu.com)](https://zhuanlan.zhihu.com/p/408027026)](https://zhuanlan.zhihu.com/p/408027026)
同时也使用了思源官方的同步同步思源笔记的数据，成功在另外一台电脑上同步了数据，并且功能一切正常。后面就发现原来的电脑上思源笔记中无法打开Zotero了，然后我尝试删掉软连接，恢复原来的storage，还是不行，重启或重新安装也不行。请问这是什么原因呢
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/44319749/ba6de513-43b4-452e-bb03-20ae4cf82f87)
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/44319749/24763ee4-a885-47c7-a8b5-dc91474ad41a)

**Comment by WingDr** [comment]
这个是zotero的问题啊，能不能试试重装zotero？我查到这个代码的意思好像是找不到应用程序。你可以把这个链接复制到浏览器里试试，正常情况下浏览器会打开zotero，但是估计你现在这个情况不太行，不是思源或者插件的问题的

**Comment by dtxdtx** [comment]
浏览器里确实也打不开，我再找找原因吧，谢谢了

**Comment by WingDr** [comment]
嗯嗯，我的建议是重装zotero，大概是软件不在系统记录里的位置了，所以没办法直接唤起

**Comment by dtxdtx** [comment]
重装到其他目录下解决了，原因还是不清楚，我并没有移动过zotero的安装目录和文献库目录。算了解决了就行

**Comment by WingDr** [comment]
okk，解决了就好
