### ISSUE TITLE
作为导致快捷键面板空白的元凶，自行忏悔

### ISSUE THREAD

**Issue by WingDr** [WingDr/siyuan-plugin-citation#56]
简单来说因为放置在onLayoutReady中的代码对onload中的代码有依赖，当某种情况下刷新导致onLayoutReady中的代码先运行的时候，会出现错误，然后插件的快捷键设置就会有问题，进而导致思源的快捷键面板空白

等有空了测试下把读取文献库的代码还是放到onload里面（很久之前测试是有问题的）

**Comment by Achuan-2** [comment]
只要在开发者工具，刷新思源，就会导致插件命令面板空白

**Comment by WingDr** [comment]
> 只要在开发者工具，刷新思源，就会导致插件命令面板空白

收到，修改之后用这个场景检验

**Comment by WingDr** [comment]
破案了，快捷键面板空白的原因是customHotKey没设定，现在直接设定成空值应该就没问题了
