### ISSUE TITLE
是否考虑增量刷新文献内容?

### ISSUE THREAD

**Issue by Nyeilim** [WingDr/siyuan-plugin-citation#57]
每次刷新时, 有些块的虽然内容一样, 但是块 ID 会变; 如果在刷新前有指向该块的链接(主要是针对 annotations 的), 则刷新后链接失效;
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/33322256/edea6b52-238a-4c98-9ffd-9e481c8c704f)

**Comment by WingDr** [comment]
增量要考虑的东西太多了，还要考虑模板变化，按照目前的思路应该是不会考虑了。

如果是做了annotation想要引用做笔记的话，其实可以把提取的annotation复制到User Data里，那里的所有东西都不会刷新（ID也不会刷新）
