### ISSUE TITLE
老的思源文献内容文档突然无法使用「刷新文献内容」等功能

### ISSUE THREAD

**Issue by QMike0** [WingDr/siyuan-plugin-citation#58]
思源v2.10.16，citation插件v0.3.3

插入引用后自动生成的文献内容文档突然无法使用「刷新文献内容」、「重新载入数据库」等功能，会报出下述错误：
> 上周还是好好的。。。

![image](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/395fb22f-cdf2-4ec4-aef8-f5bee7bf8520)
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/207b82c1-a75c-47c5-bf24-d2963455bf9e)

经测试，思源和zotero之间通过citation插件的连接是正常的，可以正常引用文献和生成文献内容文档。而且zotero条目中的siyuan链接点击后可以正常跳转到思源相应的文献内容文档中

问题可能是，之前生成的所有文献内容文档都没有被citation插件正常识别，表现为在它们的`更多-插件`中没有给出「刷新文献内容」选项，而现在新生成的文献内容文档可以被正常识别：
- 之前生成的文献内容文档
- ![image](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/33a0074b-bb9f-4e10-a92a-2069111e7f42)
- 现在新生成的文献内容文档
- ![image](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/6666bfcc-9f66-4f16-95bf-ce31092c46a8)

而且，对之前引用过的文献进行重复引用后，并没有像以前那样正常刷新对应「文献内容文档」的内容，而是新生成了文档，也说明老的「文献内容文档」没有被citation插件识别

> 感觉很奇怪，在此期间没有变动过citation插件和zotero的debug-bridge插件的设置，突然就出现这个问题...

**Comment by WingDr** [comment]
先确认下设置里面对不对，尤其是笔记本和文献库路径，然后关闭再打开插件（或者重新启动思源），再看看文献内容文档有没有“刷新文献内容”，插件会在启动的时候读取文献库里的文档构成文献的key和文档id的对应，可能是启动的时候哪里出问题了

**Comment by QMike0** [comment]
设置应该没有问题，不然也就不能自动生成新的文献内容文档；已经尝试了重启思源/重装思源/重启插件/重装插件，都无法正常生效
这是我的设置：
![设置界面](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/7f8ccdd0-1ec1-4e85-8a13-94511bd7bd29)
这是我的文档树对应笔记本和存放文献内容文档的地方：
![文档树](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/e26adeec-67fc-42f3-84ec-3ac58a1a6289)

然后，我发现个很神奇的现象，原本能正常被识别的新生成的文献内容文档，在「刷新文献内容」后，也变成了无法被插件识别
![1](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/4efb29a1-c3b8-4056-9802-d219217f71c2)
至此，我有点明白为啥老的文献内容文档都不能被插件识别：我用了「刷新全部文献内容」的功能，然后它们都像这个文档一样变成了无法正常识别的状态...

**Comment by QMike0** [comment]
佬，我大概定位出问题了，是思源新版本v2.10.16导致的

我重装了v2.10.15，再次重新引用论文，新生成的文献内容文档在「刷新文献内容」后就不会出现无法被插件识别的问题，如下
![1](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/d33b9b89-c63e-4f2c-b795-abbd9e0989df)

重新「刷新全部文献内容」，原先老的文献内容文档也可以重新被识别出来

大佬啥时候有空做下适配新版本，我就先在思源v2.10.15不升级了...

**Comment by WingDr** [comment]
嘶，确实是这个问题，不知道思源更新了什么导致sql查找文献库文献的请求寄了，我去问问D大咋回事

**Comment by WingDr** [comment]
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/63407442/e6129aa0-cbe1-4b18-bfe6-01e8724ee8ad)

已经推了新的更新，我这2.10.16看起来已经没问题了，可以放心更新思源了

**Comment by QMike0** [comment]
欧克，测试了一下确实可以了

谢谢佬~
