### ISSUE TITLE
containerTitleShort字段无效

### ISSUE THREAD

**Issue by jamy3531** [WingDr/siyuan-plugin-citation#59]
首先感谢作者带来这个很棒的插件，使得在思源笔记本中引用文献变得非常方便。

我有时候引用文献想带上期刊名字，但是为了减少空间占用，想使用Journal Abbreviation,我在插件的**index.js**文件里面发现有**containerTitleShort**这个字段，但是在文献内容模板和引用模板使用之后，发现没有生效(对应Zotero item的Journal Abbr项是有数据的),请问这个是插件的问题，还是其他方面的问题?

我的使用环境是: MacOS 14, Zotero 6, debug-brige 2.0.0, 思源笔记 2.11.1, siyuan-plugin-citation 0.3.4.

**Comment by WingDr** [comment]
抱歉，我最近不太方便改代码，你暂时先试试用`entry.containerTitleShort`，应该这样没问题。主要原因是我代码里没有把`containerTitleShort`暴露给模板，但是是已经记录了的

**Comment by jamy3531** [comment]
> 抱歉，我最近不太方便改代码，你暂时先试试用`entry.containerTitleShort`，应该这样没问题。主要原因是我代码里没有把`containerTitleShort`暴露给模板，但是是已经记录了的

我试了下，这个管用,谢谢!

**Comment by WingDr** [comment]
> 我试了下，这个管用,谢谢!

okk，暂时先这样，等我有空写码了就加
