### ISSUE TITLE
Note 部分的链接点击后无法会跳到zotero文档上的具体位置

### ISSUE THREAD

**Issue by ethan1010** [WingDr/siyuan-plugin-citation#64]
Note 部分的链接点击后无法会跳到zotero文档批注的具体位置，这是为啥？

好像插入一个链接就可以实现回跳：
zotero://open-pdf/library/items/4VYMJ9TI?page=1&annotation=K8XAIL5P

**Comment by WingDr** [comment]
note部分的链接是用zotero better note插件支持的，是个历史遗留问题，我在考虑要不要换成定位到笔记条目上的链接，暂时先别管它吧
