### ISSUE TITLE
Following the change of BBT's json-rpc

### ISSUE THREAD

**Issue by lixiao00093** [WingDr/siyuan-plugin-citation#65]
![图片-p45wyVz](https://github.com/WingDr/siyuan-plugin-citation/assets/133181634/a72142bf-eb37-4dfc-899a-c1b95e76a702)
This error occur when I add a citation using "/add". I was wondering what is the reason of this error. I have installed the Better BibTex in Zetero, and everything is OK several weeks ago.
The version of the Siyuan is 2.12.0. The version of siyuan-plugi-citation is 0.3.4.
Thank you very much.

**Comment by WingDr** [comment]
I haven't changed these codes for several months ... It seems like an error of zotero's profile. Maybe cause by some plugins (especially those who change the appearance of zotero). Have you ever installed other plugins recently?

By the way, It is similar to the situation of [this discussion](https://forums.zotero.org/discussion/109677/zotero-7-beta-xml-parsing-error-no-root-element-found), which may be helpful.

**Comment by lixiao00093** [comment]
Thank you very much! I have tried the debug-bridge way. It works perfect! I feel great! Thank you very much for developing this plugin and sharing it.
