### ISSUE TITLE
文献引用后无法再被引用

### ISSUE THREAD

**Issue by WingDr** [WingDr/siyuan-plugin-citation#66]
[https://github.com/WingDr/siyuan-plugin-citation/issues/49#issuecomment-1873307714](https://github.com/WingDr/siyuan-plugin-citation/issues/49#issuecomment-1873307714)

> 一篇文献在siyuan里引用过后就不能再次引用了，搜索框里会显示目标文献已经选中过的样子，不论再次点击还是回车都无法创建第二个引用。

**Comment by WingDr** [comment]
@Lingyu-Meng 方便说一下具体的配置吗？使用的是better-bibtex插件还是debug-beidge插件的方式？

**Comment by Lingyu-Meng** [comment]
debug-beidge 运行在Mac OS上，不过这个问题现在解决了。不知道什么缘故，已经可以多次引用了。

**Comment by WingDr** [comment]
okk，再有问题再说
