### ISSUE TITLE
文献条目名称是否可以自定义？

### ISSUE THREAD

**Issue by Junbin6** [WingDr/siyuan-plugin-citation#7]
感谢大大开发的插件。
目前正在摸索使用中。
在文献库模版设置中是否可以设置文献条目名称？目前的条目是第一作者的姓+title部分文字+年份，而且各个部分之间没有空格，看着十分别捏。
另外，希望大大可以提供一个带案例的使用教程。
非常感谢！

**Comment by Junbin6** [comment]
另外手动更改文献库中的条目会导致引用文献处同时更改（应该是直接使用了思源的直接引用）
（抱歉啊，没怎么接触过程序类的项目，只能简单描述问题）

**Comment by WingDr** [comment]
这个条目的名称是你的文献的citekey，是很重要的唯一标识，最好不要改，如果你觉得这个东西看着不爽的话可以在zotero的better bibtex插件设置里面改citekey的格式，因为这个涉及到索引文献和处理，所以这个地方不太能自定义，非常抱歉。

案例的使用教程我已经在写README了，之后可能会在b站上发个视频，等v0.0.4更新之后应该都会完善

**Comment by Junbin6** [comment]
> 这个条目的名称是你的文献的citekey，是很重要的唯一标识，最好不要改，如果你觉得这个东西看着不爽的话可以在zotero的better bibtex插件设置里面改citekey的格式，因为这个涉及到索引文献和处理，所以这个地方不太能自定义，非常抱歉。
> 
> 案例的使用教程我已经在写README了，之后可能会在b站上发个视频，等v0.0.4更新之后应该都会完善

谢谢解惑，之前只在word和google docs上用，没注意这个key.
非常期待您的教程

**Comment by WingDr** [comment]
> 感谢大大开发的插件。 目前正在摸索使用中。 在文献库模版设置中是否可以设置文献条目名称？目前的条目是第一作者的姓+title部分文字+年份，而且各个部分之间没有空格，看着十分别捏。 另外，希望大大可以提供一个带案例的使用教程。 非常感谢！

现在条目的名称可以修改了，citekey现在被放到了文档的命名（属性）里面，更新到0.0.5版本的插件之后，重新载入数据库，重启思源，然后应该就能更新好了。README你看看，如果不懂的多的话我再出视频教程（现在感觉README已经很详细了，视频只不过是指出具体位置在哪里）

**Comment by Junbin6** [comment]
非常感谢～已更新尝试，越来越好用了（之前也按建议更改了citekey的格式）
