### ISSUE TITLE
插件好像会添加额外的标签

### ISSUE THREAD

**Issue by TangQi001** [WingDr/siyuan-plugin-citation#73]
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/67812425/c91567cd-5adb-4bde-9d2f-fc1f38c26b98)
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/67812425/de0a2c4e-8d47-4b66-a76c-d222780d13c9)

**Comment by WingDr** [comment]
这个标签的正文是什么样子的？理论上这些信息都应该被塞到属性里才对。或者是你用的模板导致的这个问题

**Comment by WingDr** [comment]
抱歉，我想问的是：它既然有标签的话应该是出现在了某个文档的某个地方（应该是文献内容文档），能不能找到它出现在哪里让我帮我截个图？感谢

**Comment by WingDr** [comment]
嘶……这是笔记的HTML块啊，理论上不应该被识别成标签才对。我有空看下吧，感谢反馈

现在可以先把模板里面note的部分删掉，这样这个东西就不会被导入了，可能这块还是有点问题

**Comment by WingDr** [comment]
那我懂了，这个东西把自定义属性也提取出来了，应该是在ial属性里，然后sql查询把这个东西查出来，又被识别成了标签。

但是这个我也没办法解决orz这个属性得存在，之后的功能会用到。这应该算是思源本体的bug，就是sql提取出来的东西被识别成正文和标签了
