### ISSUE TITLE
添加引用无反应

### ISSUE THREAD

**Issue by YiHui-Liu** [WingDr/siyuan-plugin-citation#74]
![siyuan](https://github.com/WingDr/siyuan-plugin-citation/assets/30190271/b6f2699c-de1c-449b-8636-4d910bfd05d9)

* Zotero：6.0.30
* Better Bibtex：6.7.143
* Siyuan：3.0.2
* siyuan-plugin-citation：v0.3.4

点击引用后没有反应，而且中间卡顿很久才会弹出窗口（gif中剪去了很多），[社区](https://ld246.com/article/1688908419920)存在类似问题：
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/30190271/b122f3f4-0c04-4b46-93df-8a95c6b6427d)

Better Bibtex 报错：
```
[JavaScript Error: "XML Parsing Error: no root element found
Location: https://s3.ap-southeast-1.amazonaws.com/ping
Line Number 1, Column 1:" {file: "https://s3.ap-southeast-1.amazonaws.com/ping" line: 1}]
```

**Comment by WingDr** [comment]
收到，BBT的问题和 #65 相同，我现在在尝试解决
