### ISSUE TITLE
Note部分没内容，命令面板命令不显示

### ISSUE THREAD

**Issue by TangQi001** [WingDr/siyuan-plugin-citation#77]
issue 1
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/67812425/6e2fc4d6-1cc0-417a-8ce6-eb17bdb8b59e)
作者大大，从 更多-刷新文献内容 之后，note里面的笔记就不见了
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/67812425/adff5cfa-f812-40e8-9e04-e83eccbb23b0)
第一次引用的时候是有文字内容，但是图片内容没有现实
刷新一下就没note了

issue 2
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/67812425/60e800d2-4353-48b8-8273-7eeb4aa70a35)
还有min命令面板中找不到文献引用插件的内容

**Comment by WingDr** [comment]
笔记没内容是因为统一插入的时候没办法同时插入HTML块（被D大限制了），所以需要先用`{{note0}}`这样的占位符把位置占好，然后后台刷新块内容，可以多等会儿。笔记没图片也是正常的，因为zotero的笔记直接是富文本，传过来的是一大坨HTML内容，图片的链接就藏在里面，而且是zotero的内部链接，我现在没有很好的方法去处理它，可能要等思源的自定义块出来之后再看。

命令面板里丢失插件内容应该是初始化的时候出问题了，可以请你看一下`主菜单->开发者工具->控制台(Console)`里面是否有红色的错误，然后帮我截一下吗？

**Comment by WingDr** [comment]
笔记没内容是因为统一插入的时候没办法同时插入HTML块（被D大限制了），所以需要先用`{{note0}}`这样的占位符把位置占好，然后后台刷新块内容，可以多等会儿。笔记没图片也是正常的，因为zotero的笔记直接是富文本，传过来的是一大坨HTML内容，图片的链接就藏在里面，而且是zotero的内部链接，我现在没有很好的方法去处理它，可能要等思源的自定义块出来之后再看。

命令面板里丢失插件内容应该是初始化的时候出问题了，可以请你看一下`主菜单->开发者工具->控制台(Console)`里面是否有红色的错误，然后帮我截一下图吗？

**Comment by WingDr** [comment]
嘶……我以为这个问题已经解决了，重启思源也是这样的吗？

**Comment by WingDr** [comment]
okk，note的问题我之后再想办法
