### ISSUE TITLE
用户数据引用格式可能存在的问题

### ISSUE THREAD

**Issue by QMike0** [WingDr/siyuan-plugin-citation#78]
插件已更新为v0.3.7，思源也是最新版
在首次引用文献生成文献内容文档时，文档开头的用户数据引用仍是块引用的形式，并且它后面有`---`，只有「刷新文献内容」后才会正常转换为思源块链接的形式
如下：
> 我把思源块引用的动态锚文本改成了蓝底白字的样式，所以一开始的那个就是块引用

![1](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/1560586c-3ddf-4585-9c02-aff6dbe88915)

大佬有空看一下哈，感觉应该是个bug

**Comment by WingDr** [comment]
okk，应该是哪里写漏了，我去看下

**Comment by QMike0** [comment]
好的好的

另外想问下佬，现在改成根据用户数据标题的自定义属性判断用户数据的话，那文档开头的用户数据引用是不是可以删除了呢？

**Comment by WingDr** [comment]
对的，但是我现在还在修bug和写一些更重要的功能，所以暂时还没加设置界面的开关（整个设置界面的代码估计都要重构），之后肯定会加的

**Comment by QMike0** [comment]
好的，佬辛苦了:)

还想问下debug-bridge最新版是在哪里下载呀？Readme中的链接失效了，在网上直接搜索也只能在一些教程里面找到旧版本的下载链接
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/43239563/e20f9729-7eae-414d-81fc-925b82f70b9a)

**Comment by WingDr** [comment]
下面那个大佬写的 run javascript in zotero 里有旧版的debug-bridge的链接，然后最新版的在这个插件开发者的[release](https://github.com/retorquere/zotero-better-bibtex/releases?q=debug-bridge&expanded=true)里，但是最新版的一个是只适用于zotero 7，另一个是要注意我在README里面写的，在zotero里的设置和旧版不一样

**Comment by WingDr** [comment]
README里的链接我下次一块更新吧

**Comment by QMike0** [comment]
欧克，多谢~
