### ISSUE TITLE
引用链接失效

### ISSUE THREAD

**Issue by Cheng7966** [WingDr/siyuan-plugin-citation#83]
不知道为什么，之前的引用链接失效了，但是新的链接可以生成。
![Uploading 屏幕截图 2024-07-12 090324.png…]()

**Comment by WingDr** [comment]
你的图裂了……具体是啥情况？看一下引用链接对应的文件还在不在？（就是文档树里放文献的那个地方是不是有两个你引用的这个文献）

**Comment by Cheng7966** [comment]
有的，现在新插入的是正常的，就是之前三篇不知道为什么链接失效了
![屏幕截图 2024-07-12 152638](https://github.com/user-attachments/assets/bfb5e9fa-5309-4908-83c0-9fd5ae7f6146)

**Comment by WingDr** [comment]
emmm你试试在另外的地方重新插入这三篇文献，看看会不会新产生文献库里的文件。如果没有新产生（就还是刷新原本的文件）的话就没啥问题，引用失效重新引一下应该就行；如果是新产生了的话那就有点问题了，得看看是不是什么情况下触发的bug

**Comment by Cheng7966** [comment]
没有新的产生

**Comment by WingDr** [comment]
okk那就应该是这两个链接出问题了，应该没啥大问题（而且应该也不是这个插件的问题），正常用就行。如果不放心的话，下次再出这种问题注意一下操作了什么，能不能复现，然后我可以帮忙看看是因为啥
