### ISSUE TITLE
插入文献笔记没有反应

### ISSUE THREAD

**Issue by Cheng7966** [WingDr/siyuan-plugin-citation#84]
我看有插入独立笔记的选项，出现搜索框可以搜索到笔记项目，但是点击后没有反应，无法插入。

<img width="559" alt="屏幕截图 2024-07-12 161117" src="https://github.com/user-attachments/assets/2f5a1636-55f5-4c99-bb56-26b147bec8d0">

**Comment by WingDr** [comment]
按下快捷键ctrl+shift+i 看看点击的时候控制台有没有飘红的？我刚才试了一下发布版本在我这没问题

![image](https://github.com/user-attachments/assets/beeb2d36-03a7-4253-881a-d4ba783f9f24)

而且 要注意一下你选择的条目是不是含有笔记的，指的是这种在zotero仓库中有单独的笔记附件的条目，搜索的时候并不会筛选

![image](https://github.com/user-attachments/assets/aadeacd1-846e-4f1f-9348-2c5bca855424)

**Comment by Cheng7966** [comment]
好的，谢谢

**Comment by Cheng7966** [comment]
试了一下，还是不行

<img width="328" alt="独立笔记" src="https://github.com/user-attachments/assets/e570ba5b-5253-4fe6-b292-b0cbcf9cc46f">

<img width="758" alt="搜索" src="https://github.com/user-attachments/assets/af5743d2-11d5-468f-8186-25eb065e0e4f">

<img width="1600" alt="控制台报错" src="https://github.com/user-attachments/assets/f0a571f9-c94c-46f0-ae86-115c10b24b14">

控制台有报错：
POST http://127.0.0.1:23119/debug-bridge/execute?password=CTT 500 (Internal Server Error)
eval @ plugin:siyuan-plugin-citation:800
xhr @ plugin:siyuan-plugin-citation:800
er @ plugin:siyuan-plugin-citation:800
request @ plugin:siyuan-plugin-citation:800
eval @ plugin:siyuan-plugin-citation:798
eval @ plugin:siyuan-plugin-citation:914
eval @ plugin:siyuan-plugin-citation:914
Ba @ plugin:siyuan-plugin-citation:914
sendRequest @ plugin:siyuan-plugin-citation:914
eval @ plugin:siyuan-plugin-citation:97
r @ plugin:siyuan-plugin-citation:49
Promise.then (async)
t @ plugin:siyuan-plugin-citation:49
eval @ plugin:siyuan-plugin-citation:49
__async @ plugin:siyuan-plugin-citation:49
_callZoteroJS @ plugin:siyuan-plugin-citation:96
eval @ plugin:siyuan-plugin-citation:88
eval @ plugin:siyuan-plugin-citation:49
__async @ plugin:siyuan-plugin-citation:49
getNotesByItemKey @ plugin:siyuan-plugin-citation:88
eval @ plugin:siyuan-plugin-citation:65
r @ plugin:siyuan-plugin-citation:49
Promise.then (async)
t @ plugin:siyuan-plugin-citation:49
eval @ plugin:siyuan-plugin-citation:49
__async @ plugin:siyuan-plugin-citation:49
getCollectedNotesFromKey @ plugin:siyuan-plugin-citation:65
eval @ plugin:siyuan-plugin-citation:816
eval @ plugin:siyuan-plugin-citation:816
Q @ plugin:siyuan-plugin-citation:816
eval @ plugin:siyuan-plugin-citation:816
eval @ plugin:siyuan-plugin-citation:816
eval @ plugin:siyuan-plugin-citation:816
Q @ plugin:siyuan-plugin-citation:816
insertNotesBySelection @ plugin:siyuan-plugin-citation:816
P @ plugin:siyuan-plugin-citation:115
plugin:siyuan-plugin-citation:65 Uncaught (in promise) TypeError: m.map is not a function
    at ZoteroDBModal.eval (plugin:siyuan-plugin-citation:65:434)
    at Generator.next (<anonymous>)
    at r (plugin:siyuan-plugin-citation:49:21454)
eval @ plugin:siyuan-plugin-citation:65
r @ plugin:siyuan-plugin-citation:49
Promise.then (async)
B @ plugin:siyuan-plugin-citation:816
eval @ plugin:siyuan-plugin-citation:816
Q @ plugin:siyuan-plugin-citation:816
insertNotesBySelection @ plugin:siyuan-plugin-citation:816
P @ plugin:siyuan-plugin-citation:115
main.15a579c0ab345452accb.js:3205 Failed to decode downloaded font: http://127.0.0.1:51934/plugins/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/LXGWWenKaiGB-Regular.woff2
af @ main.15a579c0ab345452accb.js:3205
Xt @ main.15a579c0ab345452accb.js:3205
resize @ main.15a579c0ab345452accb.js:4133
(anonymous) @ main.15a579c0ab345452accb.js:4158
(anonymous) @ main.15a579c0ab345452accb.js:4158
setTimeout (async)
Qt @ main.15a579c0ab345452accb.js:4158
(anonymous) @ main.15a579c0ab345452accb.js:6705
setTimeout (async)
(anonymous) @ main.15a579c0ab345452accb.js:6705
main.15a579c0ab345452accb.js:3205 Failed to decode downloaded font: http://127.0.0.1:51934/plugins/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/LXGWWenKaiGB-Regular.woff2
af @ main.15a579c0ab345452accb.js:3205
Xt @ main.15a579c0ab345452accb.js:3205
resize @ main.15a579c0ab345452accb.js:4133
(anonymous) @ main.15a579c0ab345452accb.js:4158
(anonymous) @ main.15a579c0ab345452accb.js:4158
setTimeout (async)
Qt @ main.15a579c0ab345452accb.js:4158
(anonymous) @ main.15a579c0ab345452accb.js:6705
setTimeout (async)
(anonymous) @ main.15a579c0ab345452accb.js:6705
main.15a579c0ab345452accb.js:3205 OTS parsing error: cmap: Failed to parse table
af @ main.15a579c0ab345452accb.js:3205
Xt @ main.15a579c0ab345452accb.js:3205
resize @ main.15a579c0ab345452accb.js:4133
(anonymous) @ main.15a579c0ab345452accb.js:4158
(anonymous) @ main.15a579c0ab345452accb.js:4158
setTimeout (async)
Qt @ main.15a579c0ab345452accb.js:4158
(anonymous) @ main.15a579c0ab345452accb.js:6705
setTimeout (async)
(anonymous) @ main.15a579c0ab345452accb.js:6705
main.15a579c0ab345452accb.js:3205 OTS parsing error: cmap: Failed to parse table
af @ main.15a579c0ab345452accb.js:3205
Xt @ main.15a579c0ab345452accb.js:3205
resize @ main.15a579c0ab345452accb.js:4133
(anonymous) @ main.15a579c0ab345452accb.js:4158
(anonymous) @ main.15a579c0ab345452accb.js:4158
setTimeout (async)
Qt @ main.15a579c0ab345452accb.js:4158
(anonymous) @ main.15a579c0ab345452accb.js:6705
setTimeout (async)
(anonymous) @ main.15a579c0ab345452accb.js:6705

**Comment by WingDr** [comment]
不是这种独立笔记，独立笔记应该是搜索不到的，是指条目的笔记，当初做出来是方便有的人需要把笔记誊到思源上。独立笔记理论上我是筛选掉的，大概是zotero更新了条目类型的说明……

**Comment by Cheng7966** [comment]
好的，谢谢
