### ISSUE TITLE
与Zotero插件 Ethereal Style中的#Tags联用

### ISSUE THREAD

**Issue by Cheng7966** [WingDr/siyuan-plugin-citation#85]
请问可以只输出带有#的标签吗？并且输出后转换为思源标签

**Comment by WingDr** [comment]
你在zotero里添加的什么标签，到思源里就会是什么标签。在zotero里用#括住标签，到思源里就会自动转换（主要是因为zotero style插件的#标签写法和思源不一样，所以在zotero里创建标签的时候要在后面多加上一个#）

比如我在zotero里这样设置标签：
![image](https://github.com/user-attachments/assets/4b83bcf8-f665-4d1c-ba4c-b2088c49b9a8)
在zotero的目录里就会这样显示：
![image](https://github.com/user-attachments/assets/dc1dbdbf-a866-4687-b56e-f0d6db5f4c26)
然后输入到思源里就是这样的标签：
![image](https://github.com/user-attachments/assets/a357c060-1cf8-4148-a25d-ca85af918fac)

**Comment by Cheng7966** [comment]
好的，谢谢！是想着后面的#看看能不能在导入思源是加入的，这样Zotero上面就没有后面的#，看着整齐一点，这样子也可以。

**Comment by WingDr** [comment]
嗯嗯，我最开始也想做转化，但是想到其实zotero自身的标签是不带#的，这个#Tag也只是那个插件的作者自己写的，非要做转换的话很容易会有各种冲突。最后仔细考虑了还是没做，这样就是显示效果有点瑕疵，但是绝对不会出问题
