### ISSUE TITLE
tag模板写法

### ISSUE THREAD

**Issue by Cheng7966** [WingDr/siyuan-plugin-citation#86]
你好，我在使用模板的时候，想要将Zotero的#开头的tag自动变成思源的tag格式，由于我不会编程，所以参考了帮助文档后，让AI帮我写了一段JavaScript代码：`tags.length ? `\n**Tags**: ${tags.map(tags => tags.startsWith('#') ? `${tags}#` : tags).join(', ')}` : "";`，但是并没有成果，提示template.js error。可以帮我看看吗？
这是JavaScript代码图片：
![image](https://github.com/user-attachments/assets/608fff57-8fed-445a-b3b1-20cccd4fb334)
这是在网页JavaScript编辑器运行结果，是可以的：
![image](https://github.com/user-attachments/assets/e50a701a-535d-4034-abd0-f7145593887e)
这是思源插件的模板设置：
![image](https://github.com/user-attachments/assets/d6cf4801-0ce4-4111-af7d-1ea3003f7967)
这是思源文献内容刷新后结果：
![image](https://github.com/user-attachments/assets/a2672919-301d-401f-8421-1f1868e7f9ef)

**Comment by WingDr** [comment]
我知道了，你测试用的数据和我给的不一样，我给的直接是一个字符串，所以应该这么写，我测试了应该没问题

```javascript
{{ tags.length ? `\n**Tags**: ${tags.split(", ").map(tags => tags.startsWith('#') ? `${tags}#` : tags).join(', ')}` : "" }}
```

**Comment by Cheng7966** [comment]
是的可以了，谢谢
