### ISSUE TITLE
Notes保留markdown格式

### ISSUE THREAD

**Issue by Cheng7966** [WingDr/siyuan-plugin-citation#87]
开发者您好，感谢您的插件！
我有个问题是，文献笔记（模板中的`{{note}}`）导入到思源里面，好像是HTMML嵌入，这样只能作为整体引用，能直接变成markdown吗？我想要引用文献笔记中的自己写的某个小标题。
![Snipaste_2024-09-09_22-44-06](https://github.com/user-attachments/assets/ba49842a-66da-4866-bdba-14184bcdf27b)

**Comment by WingDr** [comment]
抱歉，这个东西我试过，因为zotero直接给出的是html格式的富文本，虽然可以直接交给思源解析但是会出现非常多的问题（zotero自己的富文本编辑器和思源的markdown编辑器规范不一样），所以后来为了保证可读性还是决定作为整个HTML块导入。如果想要誊到思源上引用的话建议还是自行复制（到用户数据区域就不会被刷新）然后修正可能出现的解析错误。

后续如果有可能的话或许可以用zotero的编辑器解析或者找到方法从zotero中直接获得markdown版本，但是就需要花很长时间研究，并不排在有限解决的问题里
