### ISSUE TITLE
提示框会阻塞思源的打开

### ISSUE THREAD

**Issue by Nyeilim** [WingDr/siyuan-plugin-citation#89]
![image](https://github.com/user-attachments/assets/272ca198-cd70-4a83-a424-77f57df51d87)
如题，每次打开思源就会弹这个框，然后必须要点确定后思源才能开。希望改成异步的，或者可以取消显示。我记得之前好像没有这种情况，是哪个版本加上的吗？

**Comment by WingDr** [comment]
啊？你这是啥环境，插件应该都是在思源加载完成后初始化啊，不应该这样的

**Comment by Nyeilim** [comment]
Windows 11, siyuan v3.1.6, siyuan-plugin-citation v3.0.9, zotero 未开启；啊原来只有我这样吗？

**Comment by WingDr** [comment]
貌似是的……我的插件里的提醒都是使用的官方给的接口，应该不会出现这种问题，要不排查一下是不是别的插件的问题？

**Comment by Nyeilim** [comment]
我把插件全关了，把主题换回原生主题，还是有问题。

**Comment by WingDr** [comment]
主要是我对这个问题一点头绪都没有orz因为这个通知所在的部分直接就是放在一个异步运行的函数里的，理论上根本不可能阻塞，看看要不要在思源本体那边问一下这个问题，不知道D大有没有debug的方法

通知所在的功能的代码是这一行，直接就是异步的
![image](https://github.com/user-attachments/assets/3a41b470-a3ec-4c46-aeef-e5714e1158d8)

**Comment by WingDr** [comment]
讲真，我到现在都没有遇到过别人有这问题，太神奇了。我觉得可以试试退回思源版本或者退回这个插件的版本。这部分的代码我应该从前年就没动过了，要有问题早就提出来了，有可能是思源本体改了那些东西导致的，或者是你的某些特殊的运行环境导致的

**Comment by Nyeilim** [comment]
嗯... 我用另外个笔记本打开试试看

**Comment by WingDr** [comment]
嗯嗯，我看到你去年十月就在这里提出过issue了，这个问题是突然出现的吗？

**Comment by Nyeilim** [comment]
好像是前几个版本开始？我也记不太清，我去思源那里提个 issue。

**Comment by WingDr** [comment]
好，我也follow一下，看看是不是插件的流程改了，那我这也得更新

**Comment by Nyeilim** [comment]
嗯，这是[链接](https://github.com/siyuan-note/siyuan/issues/12476)
