### ISSUE TITLE
文献笔记模版的问题

### ISSUE THREAD

**Issue by wangfh5** [WingDr/siyuan-plugin-citation#9]
我之前是使用zotero插件[mdnotes](https://github.com/argenos/zotero-mdnotes)来导出markdown格式的文献笔记的, 对比起来目前citation的模板还是很简陋, 

1. 缺少一些重要的变量, 如zotero PDF附件的跳转链接, 所处文件夹, 打了什么标签, 条目的类型(article还是preprint等等). 
2. 填写模版的时候, 如 {{year}} 只是内容 2018, 没有自动转化为 `- year: 2018` 这种markdown语法. 有一个好处是可以自己任意调整, 但是如果文献没有这个信息, 就会出现一行空荡荡的`- `. 
![image](https://github.com/WingDr/siyuan-plugin-citation/assets/51868839/3593b294-5e2f-4876-a901-bc7dfe74f9fb)
而在mdnotes中, 模版里面的域{{Date}}渲染出来就是`- Date: 2022-03-21`, 如果文献源信息里没有这个, 就不会出现这一行项目列表. 
3. 建议增加文献笔记名称的自定义功能, 现在默认创建的文献笔记名称是直接用zotero的Citekey, 但是可以加上添加前缀和后缀的功能.

**Comment by WingDr** [comment]
> 我之前是使用zotero插件[mdnotes](https://github.com/argenos/zotero-mdnotes)来导出markdown格式的文献笔记的, 对比起来目前citation的模板还是很简陋,
> 
> 1. 缺少一些重要的变量, 如zotero PDF附件的跳转链接, 所处文件夹, 打了什么标签, 条目的类型(article还是preprint等等).
> 2. 填写模版的时候, 如 {{year}} 只是内容 2018, 没有自动转化为 `- year: 2018` 这种markdown语法. 有一个好处是可以自己任意调整, 但是如果文献没有这个信息, 就会出现一行空荡荡的`- `.
>    ![image](https://user-images.githubusercontent.com/51868839/252004857-3593b294-5e2f-4876-a901-bc7dfe74f9fb.png)
>    而在mdnotes中, 模版里面的域{{Date}}渲染出来就是`- Date: 2022-03-21`, 如果文献源信息里没有这个, 就不会出现这一行项目列表.
> 3. 建议增加文献笔记名称的自定义功能, 现在默认创建的文献笔记名称是直接用zotero的Citekey, 但是可以加上添加前缀和后缀的功能.

pdf的跳转链接是{{files}}，标签和条目的类型是有这个数据的，但是我要看看bibtex和csl-json里面这个东西会怎么呈现，毕竟不是所有人都用zotero的。所处的文件夹是什么意思？

模板变量有人可能用来插入在行间内容里的，不可能直接生成列表。理论上最好模板是能够支持表达式之类的，但是这个东西我没搞懂怎么做，我可以先整一个[[]]包裹的文本如果内部的变量都没有那就整个不出现

笔记标题自定义在v0.0.5版本中已经允许了，但是有一点小bug，正在修。

**Comment by wangfh5** [comment]
> pdf的跳转链接是{{files}}，标签和条目的类型是有这个数据的，但是我要看看bibtex和csl-json里面这个东西会怎么呈现，毕竟不是所有人都用zotero的。所处的文件夹是什么意思？
> 
> 模板变量有人可能用来插入在行间内容里的，不可能直接生成列表。理论上最好模板是能够支持表达式之类的，但是这个东西我没搞懂怎么做，我可以先整一个[[]]包裹的文本如果内部的变量都没有那就整个不出现
> 
> 笔记标题自定义在v0.0.5版本中已经允许了，但是有一点小bug，正在修。

1. 我想说的PDF链接是跳转到zotero打开pdf的链接，不是本地的链接。所处文件夹是zotero里面这个文献所在的目录，不过这个重要性低一些。我觉得虽然不是所有人都用zotero，但既然有“数据库类型”的选择区域，可以辛苦一点把不同数据库下的模板支持，甚至下面的设置选项都可以微调一下。
2. 这个方案也不错，能用就行
3. 我更新了0.0.5版本，但是好像没看到有自定义笔记标题的设置区，新建文献笔记的话标题还是citekey。然后我看了更新日志，似乎只是支持自己随意更改文档标题，但我更希望的是能自定义前缀后缀来自动化新建（比如我把文献笔记文档标题都定义为了@citekey），我记得Obsidian的citation插件应该是有这个功能的。

感谢您为此插件的贡献！

**Comment by WingDr** [comment]
> 我想说的PDF链接是跳转到zotero打开pdf的链接，不是本地的链接。

这个可以有，我之前一直不知道怎么生成链接，最近刚知道的

> 所处文件夹是zotero里面这个文献所在的目录，不过这个重要性低一些。

文献是可以重复放置的吧，如果把一个项目复制到多个文件夹也判断不了他到底在哪。目前better bibtex是不提供这个信息的，不过之后如果能直接接入zotero.sqlite的话这个信息可能能得到

> 我觉得虽然不是所有人都用zotero，但既然有“数据库类型”的选择区域，可以辛苦一点把不同数据库下的模板支持，甚至下面的设置选项都可以微调一下。

不不不我的意思是我得瞅一眼bibtex和json里面生成的是什么格式的然后一块加进去，得花点时间让我试验和调整，理论上应该是都会输出的，如果没法输出的话我会做出调整的（例如现在bibtex和zotero导出的note字段就是不一样的格式，后者会有指向zotero的链接，这个我已经在做适配了）

> 我更新了0.0.5版本，但是好像没看到有自定义笔记标题的设置区，新建文献笔记的话标题还是citekey。然后我看了更新日志，似乎只是支持自己随意更改文档标题，但我更希望的是能自定义前缀后缀来自动化新建（比如我把文献笔记文档标题都定义为了@citekey），我记得Obsidian的citation插件应该是有这个功能的。

obsidian那边是纯按照文件名索引，所以文件名上必须有citekey，思源这边索引靠id，所以文件名能随意配置（甚至重复）问题就是我得找个地方存一下citekey，现在是改到了文档的“命名”（文档的属性之一）上，所以标题能够随意自定义了。

标题的自定义模板我还在整，因为这个出了之后肯定还要有一个和“刷新引用”一样的“格式化文献内容标题”，得花点时间去写

**Comment by Geo123abc** [comment]
内容很丰富啊

**Comment by wangfh5** [comment]
> 文献是可以重复放置的吧，如果把一个项目复制到多个文件夹也判断不了他到底在哪。目前better bibtex是不提供这个信息的，不过之后如果能直接接入zotero.sqlite的话这个信息可能能得到

其实导入文献笔记的时候, 是弹出一个窗口然后在文件夹里面选择文献条目, 此时的所处文件夹应该是well-defined的. 当然zotero还提供了搜索的方式, 这种就不清楚了. zotero里面的mdnotes插件导出文献笔记会得到这一条目所在的所有文件夹.

**Comment by WingDr** [comment]
> 其实导入文献笔记的时候, 我是弹出一个zotero窗口然后在各层级文件夹里面选择文献条目 (这种模式是`Preference-cite-word processor-勾选use classic Add Citation dialog), 此时的所处文件夹应该是well-defined的. 当然zotero还提供了新的搜索的方式 (即不勾选use classic Add Citation dialog), 这种就难说了.
>
>zotero的mdnotes插件导出文献笔记会得到这一条目所在的所有文件夹.

我觉得这个事情暂时不考虑了，主要是我一直用新版的都没有这个字段，应该是新老版的不一样。你说的tags和type都加上了，看看还有啥变量需要的我可以再加？另外待会儿看一下0.0.6的README，应该你说的其他的都加上了

**Comment by Geo123abc** [comment]
> 

https://www.bilibili.com/video/BV17u411j79z?t=1041.1

这两种zotero窗口样式最终效果都是一样的
并且目前citation插件好像一次只能在zotero中选择一个父文献条目插入到思源笔记中，但是这个父条目下的所有子笔记都会导入到思源笔记中（这点取决于你在citation设置中的  文献模板 ，详看   https://www.bilibili.com/video/BV17u411j79z?t=932.0   ）

**Comment by wangfh5** [comment]
> 我觉得这个事情暂时不考虑了，主要是我一直用新版的都没有这个字段，应该是新老版的不一样。你说的tags和type都加上了，看看还有啥变量需要的我可以再加？另外待会儿看一下0.0.6的README，应该你说的其他的都加上了

好的，感谢，不过思源还没推送插件更新，类似于`zotero://open-pdf/library/items/`这样的PDF附件链接有加上吗？

**Comment by wangfh5** [comment]
> https://www.bilibili.com/video/BV17u411j79z?t=1041.1
> 
> 这两种zotero窗口样式最终效果都是一样的 并且目前citation插件好像一次只能在zotero中选择一个父文献条目插入到思源笔记中，但是这个父条目下的所有子笔记都会导入到思源笔记中（这点取决于你在citation设置中的 文献模板 ，详看 https://www.bilibili.com/video/BV17u411j79z?t=932.0 ）

很好的演示视频，学习了

**Comment by WingDr** [comment]
> > 我觉得这个事情暂时不考虑了，主要是我一直用新版的都没有这个字段，应该是新老版的不一样。你说的tags和type都加上了，看看还有啥变量需要的我可以再加？另外待会儿看一下0.0.6的README，应该你说的其他的都加上了
> 
> 好的，感谢，不过思源还没推送插件更新，类似于`zotero://open-pdf/library/items/`这样的PDF附件链接有加上吗？

昨天糊涂了，没同步到github上导致没推送，我现在加的是select item的链接，主要是你说的这个链接我之前没找到orz，下个版本就加上

**Comment by WingDr** [comment]
这个issue我先关了，如果有什么新的字段需要的话直接单开issue吧，这个翻起来有点费劲了
