### ISSUE TITLE
zotero笔记中的图片，同步到思源，无法显示

### ISSUE THREAD

**Issue by chenhao1080** [WingDr/siyuan-plugin-citation#90]
变成了白色
![image](https://github.com/user-attachments/assets/0945e785-6a83-43be-9e1a-45626a1b3960)

**Comment by WingDr** [comment]
右键图片->打开->打开文件位置

帮忙看下是图片本身是白的还是没有图片？我记得思源如果没有图片的话应该不会渲染成白框，我感觉是在zotero里没提取出来文件

**Comment by chenhao1080** [comment]
这是zotero笔记内的

**Comment by WingDr** [comment]
哦哦，看错了，笔记内的图片目前确实显示不出来，因为本身用的是包装过的路径，和正常的文件相对路径不一样的

这个目前没办法解决，抱歉，之后如果能够把zotero的富文本编辑器移植到思源里或许能够做到导入然后显示，但是目前暂时也不会考虑（毕竟思源连自定义块还没做出来）

**Comment by chenhao1080** [comment]
好的，感谢，有没有什么替代方法？








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年9月23日(周一) 下午3:05写道:

  

 
哦哦，看错了，笔记内的图片目前确实显示不出来，因为本身用的是包装过的路径，和正常的文件相对路径不一样的
 
这个目前没办法解决，抱歉，之后如果能够把zotero的富文本编辑器移植到思源里或许能够做到导入然后显示，但是目前暂时也不会考虑（毕竟思源连自定义块还没做出来）

**Comment by WingDr** [comment]
我试了一下整体复制过来是没问题的（直接ctrl+c，ctrl+v）图片也会正常复制过来，如果还想要有关联的话就加一下引用应该就行，但是就没有zotero自己笔记里那种跳转到对应段落的能力了
