### ISSUE TITLE
ZOTERO7,思源插入，不显示。明明红色的选中进度条已经动完了

### ISSUE THREAD

**Issue by lin-uice** [WingDr/siyuan-plugin-citation#94]
https://github.com/user-attachments/assets/9de9ecb5-a9cc-4105-b179-9dd36db4c98c

**Comment by WingDr** [comment]
按`ctrl+shift+i`调出控制台，然后再操作一下插入，看看有没有什么报错？另外你是用什么配置的？better-bibtex还是debug-brige？

**Comment by lin-uice** [comment]
> 按`ctrl+shift+i`调出控制台，然后再操作一下插入，看看有没有什么报错？另外你是用什么配置的？better-bibtex还是debug-brige？

better bibtex。好我试一下

**Comment by lin-uice** [comment]
> 按`ctrl+shift+i`调出控制台，然后再操作一下插入，看看有没有什么报错？另外你是用什么配置的？better-bibtex还是debug-brige？

可以了，可能是那个文章的问题？（zotero中，很多文章是conference格式的，没有doi管理很麻烦）。非常感谢作者！

**Comment by WingDr** [comment]
okk，有可能是那个文章的问题，我的建议是还是看一下控制台的报错，因为这个东西是有一点逻辑冲突就会退出，所以需要把各个文章的格式协调好

**Comment by lin-uice** [comment]
> okk，有可能是那个文章的问题，我的建议是还是看一下控制台的报错，因为这个东西是有一点逻辑冲突就会退出，所以需要把各个文章的格式协调好

没有报错~~查了一下，这两篇应该是openreview中退稿的稿件（虽然退稿了，但是对我来说有用），因此文章并没有任何信息。

**Comment by WingDr** [comment]
> 没有报错~~查了一下，这两篇应该是openreview中退稿的稿件（虽然退稿了，但是对我来说有用），因此文章并没有任何信息。

好的，感谢反馈

**Comment by lin-uice** [comment]
> > 没有报错~~查了一下，这两篇应该是openreview中退稿的稿件（虽然退稿了，但是对我来说有用），因此文章并没有任何信息。
> 
> 好的，感谢反馈

感谢作者大佬的及时答疑！感谢作者这么好用的插件！
