### ISSUE TITLE
Linux里0.4.0版本无法正常插入数据库，windows可以；

### ISSUE THREAD

**Issue by BoysFight** [WingDr/siyuan-plugin-citation#96]
系统环境： ubuntu20.04
APP版本：3.1.15
问题：配置debug-bridge方式无法正常插入文献到数据库，会报
plugin:siyuan-plugin-citation:116 Uncaught (in promise) Error: open /home/dengbo/workspace/siyuan-data\data\templates\DB\papernote.md: no such file or directory
at U.eval (plugin:siyuan-plugin-citation:116:3590)
at Generator.next ()
at Dt (plugin:siyuan-plugin-citation:116:2804)

实际的数据库模板路径设置为“/data/templates/DB/papernote.md” , 同样配置下windows11系统3.1.15版本可正常使用插入文献到数据库。

**Comment by BoysFight** [comment]
![image](https://github.com/user-attachments/assets/0520bbb0-5207-4040-b946-ef36cbb90126)

**Comment by WingDr** [comment]
okk，这个我知道咋回事了，之前主要是不想用path所以直接拼接的，但是好像是windows会适应斜杠路径，linux无法适应反斜杠路径

**Comment by WingDr** [comment]
另外设置文献内容文档标题然后没法更新是啥情况？主要是那个我不知道出啥事了

**Comment by BoysFight** [comment]
> 另外设置文献内容文档标题然后没法更新是啥情况？主要是那个我不知道出啥事了

这个我还不确定，有可能是上边这个报错了导致后续有些流程没走了？

**Comment by WingDr** [comment]
有可能，那我先更新这个

**Comment by WingDr** [comment]
已经更新

**Comment by WingDr** [comment]
我帖子里的包也更新了，下载下来用就行，或者直接到pre-release里下载用

**Comment by BoysFight** [comment]
更新后正常了~

**Comment by WingDr** [comment]
> 另外设置文献内容文档标题然后没法更新是啥情况？主要是那个我不知道出啥事了

okk，这个问题还有吗？

**Comment by BoysFight** [comment]
> > 另外设置文献内容文档标题然后没法更新是啥情况？主要是那个我不知道出啥事了
> 
> okk，这个问题还有吗？

看起来也解决了

**Comment by WingDr** [comment]
好好好，那就没问题了
